import type { ChapterContent, Lang, Movement, Summary } from "../types";

// Content copied verbatim from the design handoff prototype (MV / SUM constants).
// Verse strings mark key words as [key|display text]; see content/parse.ts.
const MV: Movement[] = [
{ id: 'm1', num: 'I', range: '1–4', scene: 'radiance', art: '3D · R3F — sun volume, one god-ray toward camera, slow dolly-in. Alt: brass seal presses into gold wax.',
  en: { title: 'God has spoken by his Son', quote: '“He is the radiance of the glory of God…”', sref: 'Hebrews 1:3', cap: 'Scene: one beam leaves the sun and reaches toward you. You cannot separate the sunbeam from the sun.',
    altQuote: '“…and the exact imprint of his nature.”', altCap: 'Scene: a seal presses into warm gold wax. The mark matches the seal exactly, as the Son matches the Father.',
    snips: ['Long ago, at many times and in many ways, God spoke…', '…in these last days he has spoken to us by his Son', 'He is the radiance of the glory of God', '…as much superior to angels as the name he has inherited'],
    verses: [
      [1, 'Long ago, [ways|at many times and in many ways], God spoke to our [fathers|fathers] by the [prophets|prophets],'],
      [2, 'but in these [last|last days] he has spoken to us by his Son, whom he appointed the [heir|heir of all things], through whom also he created the world.'],
      [3, 'He is the [radiance|radiance] of the [glory|glory of God] and the [imprint|exact imprint] of his nature, and he upholds the universe by the [word|word of his power]. After making [purification|purification] for sins, he sat down at the [right|right hand of the Majesty] on high,'],
      [4, 'having become as much superior to angels as the [name|name he has inherited] is more excellent than theirs.']],
    com: [['h', 'The God who speaks'],
      ['p', 'Hebrews opens with a voice, not an argument. For centuries God spoke “at many times and in many ways”: part by part across the thirty-nine books of the Old Testament, through angels and a burning bush, through fire, thunder, cloud and earthquake, through dreams, visions and prophets. The word “fathers” tells us who first read this letter. They were Jewish believers, and this long story was their own.'],
      ['p', 'None of it was wasted. The Law was holy and came from God, but it worked like a mirror. It showed people their true spiritual condition and proved they could not be perfect in their own power. Like a strict tutor, it looked after them until the right time.'],
      ['q', '“The mirror cannot wash your face; it only shows how dirty your face is.”'],
      ['p', 'Old and New are not one covenant replacing another. They are stages of one plan. In “these last days”, between Christ’s first coming and his return, the pieces come together in one Person. Jesus did not destroy the Old Testament; he fulfilled it, writing God’s law on human hearts (Jer 31:31–34).'],
      ['h', 'Heir and maker'],
      ['p', 'The Son is appointed heir of all things. Everything is his by right of sonship. The heir is also the maker: God created the world through him, the ages and everything in them (John 1:1–3; Col 1:16–17). He is not just the last prophet in a long line. He is the one the whole line was pointing to.'],
      ['h', 'The sunbeam and the sun'],
      ['p', 'In verse 3 the language turns to light. “Radiance” is brightness beaming out from its source. Think of the sun and its beam. You cannot separate a sunbeam from the sun, and wherever the beam is, the sun is there too. The Son is not a distant reflection of God. He is God’s own glory shining out.'],
      ['p', 'He is also the “exact imprint” of God’s nature. The word first meant an engraver’s stamp, and later the mark that stamp leaves on a coin or wax seal. When the seal is pressed, the image matches exactly.'],
      ['h', 'Seated, and greater'],
      ['p', 'This Son upholds the universe by his word. He made purification for sins at the cross, then sat down at the right hand of the Majesty on high, the place of highest honour and equal authority. Jewish readers held angels in great honour, and verse 4 draws the line the rest of the chapter will prove: the Son has inherited a name, “Son”, that no angel has ever been given.']] },
  ko: { title: '하나님이 아들로 말씀하셨다', quote: '“이는 하나님 영광의 광채시요…”', sref: '히브리서 1:3', cap: '장면: 한 줄기 빛이 해에서 나와 당신에게 닿습니다. 햇살은 해와 분리될 수 없습니다.',
    altQuote: '“…그 본체의 형상이시라”', altCap: '장면: 인장이 따뜻한 금빛 밀랍에 눌립니다. 아들이 아버지와 같으시듯, 자국은 인장과 정확히 일치합니다.',
    snips: ['옛적에 여러 부분과 여러 모양으로 말씀하신 하나님이', '이 모든 날 마지막에 아들로 우리에게 말씀하셨으니', '이는 하나님 영광의 광채시요', '천사보다 더욱 아름다운 이름을 기업으로 얻으심이니'],
    verses: [
      [1, '옛적에 [prophets|선지자들]로 [ways|여러 부분과 여러 모양]으로 우리 [fathers|조상들]에게 말씀하신 하나님이'],
      [2, '이 모든 [last|날 마지막]에 아들로 우리에게 말씀하셨으니 이 아들을 [heir|만유의 후사]로 세우시고 또 저로 말미암아 모든 세계를 지으셨느니라'],
      [3, '이는 [glory|하나님 영광]의 [radiance|광채]시요 그 [imprint|본체의 형상]이시라 그의 [word|능력의 말씀]으로 만물을 붙드시며 [purification|죄를 정결케 하는 일]을 하시고 높은 곳에 계신 [right|위엄의 우편]에 앉으셨느니라'],
      [4, '그가 천사보다 얼마큼 뛰어남은 저희보다 더욱 아름다운 [name|이름]을 기업으로 얻으심이니']],
    com: [['h', '말씀하시는 하나님'],
      ['p', '히브리서는 논증이 아니라 음성으로 시작합니다. 수 세기 동안 하나님은 “여러 부분과 여러 모양으로” 말씀하셨습니다. 구약 39권에 걸쳐 조금씩, 천사와 떨기나무 불꽃으로, 불과 우레와 구름과 지진으로, 꿈과 환상과 선지자들을 통해 말씀하셨습니다. “조상들”이라는 표현은 이 편지의 첫 독자가 이 긴 이야기를 자기 역사로 알던 유대인 신자들이었음을 보여 줍니다.'],
      ['p', '그 어느 것도 헛되지 않았습니다. 율법은 하나님께서 주신 거룩한 것이지만 거울처럼 작용했습니다. 사람들에게 그들의 참된 영적 상태를 보여 주었고, 스스로의 힘으로는 온전해질 수 없음을 증명했습니다. 엄격한 가정교사처럼, 때가 이르기까지 그들을 돌보았습니다.'],
      ['q', '“거울은 얼굴을 씻어 주지 못하고, 얼굴이 얼마나 더러운지 보여 줄 뿐입니다.”'],
      ['p', '구약과 신약은 하나가 다른 하나를 폐기하는 것이 아니라, 한 계획의 단계들입니다. “이 모든 날 마지막에”, 곧 그리스도의 초림과 재림 사이의 시대에 그 조각들이 한 분께로 모입니다. 예수님은 구약을 폐하지 않으시고 완성하셨으며, 하나님의 법을 사람의 마음에 새기셨습니다(렘 31:31–34).'],
      ['h', '후사이자 창조자'],
      ['p', '아들은 만유의 후사로 세워지셨습니다. 아들 됨의 권리로 모든 것을 받으시는 분입니다. 그 후사는 창조자이기도 합니다. 하나님께서 “저로 말미암아 모든 세계를 지으셨”습니다(요 1:1–3, 골 1:16–17). 그분은 선지자들 가운데 마지막 사람이 아니라, 그 긴 흐름 전체가 가리키던 바로 그분입니다.'],
      ['h', '햇살과 해'],
      ['p', '3절은 빛의 언어를 사용합니다. “광채”는 근원에서 비추어 나오는 밝음입니다. 해와 햇살을 생각해 보십시오. 햇살은 해와 분리될 수 없고, 햇살이 있는 곳에 해도 함께 있습니다. 아들은 멀리서 하나님을 반사하는 분이 아니라, 밖으로 비추어 나오는 하나님의 영광 그 자체입니다.'],
      ['p', '그분은 또한 하나님 “본체의 형상”이십니다. 이 단어는 본래 조각가가 동전이나 인장을 새길 때 쓰는 도장을 뜻했고, 후에는 그 도장이 남긴 자국을 뜻하게 되었습니다. 인장을 누르면 형상이 완벽하게 일치합니다.'],
      ['h', '앉으신 분, 뛰어나신 분'],
      ['p', '이 아들은 능력의 말씀으로 만물을 붙드시고, 십자가에서 죄를 정결케 하신 후, 높은 곳에 계신 위엄의 우편에 앉으셨습니다. 최고의 영예와 동등한 권위의 자리입니다. 유대인들은 천사를 매우 높였고, 4절은 이 장 전체가 증명할 선을 긋습니다. 아들은 어떤 천사도 받지 못한 이름, 곧 “아들”이라는 이름을 기업으로 얻으셨습니다.']] },
  words: {
    en: {
      ways: { t: 'At many times and in many ways', g: 'polymerōs kai polytropōs · πολυμερῶς καὶ πολυτρόπως', v: '1:1', s: 'Part by part, in many forms', d: 'Many portions, part by part, across the 39 books of the Old Testament, and in many ways: angels, a burning bush, a mountain, fire, thunder, earthquake, cloud, miracles, visions, dreams.' },
      fathers: { t: 'Fathers', g: 'pateres · πατέρες', v: '1:1', s: 'The Jewish forefathers', d: 'The Jewish forefathers of the Old Testament. It suggests the first readers were of Jewish heritage.' },
      prophets: { t: 'Prophets', g: 'prophētai · προφῆται', v: '1:1', s: 'Messengers of God’s word', d: 'Messengers of God’s words to Israel. They were inspired by God to make his will known and to reveal the future.' },
      last: { t: 'Last days', g: 'eschatou tōn hēmerōn · ἐσχάτου τῶν ἡμερῶν', v: '1:2', s: 'From Christ’s coming to his return', d: 'The age between Jesus’ first coming and his Second Coming.' },
      heir: { t: 'Heir of all things', g: 'klēronomos · κληρονόμος', v: '1:2', s: 'Receives all by right of sonship', d: 'One who receives his allotted possession by right of sonship.' },
      radiance: { t: 'Radiance', g: 'apaugasma · ἀπαύγασμα', v: '1:3', s: 'The sunbeam cannot leave the sun', d: 'Reflected brightness beamed forth. The sunbeam cannot be separated from the sun: where the beam is, the sun is there too.' },
      glory: { t: 'Glory of God', g: 'doxa · δόξα', v: '1:3', s: 'His nature, power and acts', d: 'The nature, character, power and acts of God. Here it is the spiritual awe of his presence, his perfect love and infinite power.' },
      imprint: { t: 'Exact imprint', g: 'charaktēr · χαρακτήρ', v: '1:3', s: 'The seal’s perfect impression', d: 'First the engraver’s stamp for coins, seals and branding irons, then the impression itself: the exact likeness of the original.' },
      word: { t: 'Word of his power', g: 'rhēma · ῥῆμα', v: '1:3', s: 'His all-powerful command', d: 'His omnipotent command: unlimited power and infinite authority. (NIV: “sustaining all things by his powerful word.”)' },
      purification: { t: 'Purification', g: 'katharismos · καθαρισμός', v: '1:3', s: 'Cleansing from the guilt of sin', d: 'Cleansing from the guilt of sin and freeing from filth. Accomplished when he died on the cross for our sins.' },
      right: { t: 'Right hand of the Majesty', g: 'en dexia · ἐν δεξιᾷ', v: '1:3', s: 'Highest place of honour', d: 'The highest place of honour, power and authority. It stands for supreme power, royal dignity and equal status with God.' },
      name: { t: 'The name he inherited', g: 'onoma · ὄνομα', v: '1:4', s: 'The title “Son”', d: 'A title. The name Jesus inherited is “Son”, one no angel has received.' } },
    ko: {
      ways: { t: '여러 부분과 여러 모양', g: 'polymerōs kai polytropōs · πολυμερῶς καὶ πολυτρόπως', v: '1:1', s: '조금씩, 여러 방식으로', d: '구약 39권에 걸쳐 여러 번 조금씩, 그리고 여러 방식으로: 천사, 떨기나무 불꽃, 산, 불, 우레, 지진, 구름, 기적, 환상, 꿈.' },
      fathers: { t: '조상들', g: 'pateres · πατέρες', v: '1:1', s: '유대인의 조상', d: '구약의 유대인 조상들. 첫 독자가 유대인 배경의 사람들이었음을 보여 줍니다.' },
      prophets: { t: '선지자들', g: 'prophētai · προφῆται', v: '1:1', s: '하나님의 말씀을 전한 메신저', d: '하나님의 말씀을 이스라엘 백성에게 전한 메신저. 하나님의 뜻을 알리고 미래를 드러내도록 영감을 받은 사람입니다.' },
      last: { t: '날 마지막', g: 'eschatou tōn hēmerōn · ἐσχάτου τῶν ἡμερῶν', v: '1:2', s: '초림부터 재림까지', d: '예수님의 초림부터 재림까지의 시대.' },
      heir: { t: '만유의 후사', g: 'klēronomos · κληρονόμος', v: '1:2', s: '아들 됨의 권리로 받는 자', d: '아들 됨의 권리로 자기 몫의 기업을 받는 자.' },
      radiance: { t: '광채', g: 'apaugasma · ἀπαύγασμα', v: '1:3', s: '햇살은 해를 떠날 수 없다', d: '반사되어 비추어 나오는 밝음. 햇살은 해와 분리될 수 없고, 햇살이 있는 곳에 해도 함께 있습니다.' },
      glory: { t: '하나님 영광', g: 'doxa · δόξα', v: '1:3', s: '그분의 본성과 능력', d: '하나님의 본성, 성품, 능력, 행하심을 드러냄. 그분의 임재 앞에서 느끼는 영적 경외, 완전한 사랑과 무한한 능력입니다.' },
      imprint: { t: '본체의 형상', g: 'charaktēr · χαρακτήρ', v: '1:3', s: '인장의 완벽한 자국', d: '본래 동전이나 인장을 새기는 조각가의 도장을 뜻했으나, 후에는 새겨진 자국 그 자체, 곧 원본의 정확한 형상을 뜻하게 되었습니다.' },
      word: { t: '능력의 말씀', g: 'rhēma · ῥῆμα', v: '1:3', s: '전능한 명령', d: '전능한 명령. 무한한 능력과 권위를 뜻합니다.' },
      purification: { t: '정결케 하는 일', g: 'katharismos · καθαρισμός', v: '1:3', s: '죄의 허물을 씻어 냄', d: '죄의 허물을 씻어 내고 더러움에서 자유롭게 하는 것. 십자가에서 이루어졌습니다.' },
      right: { t: '위엄의 우편', g: 'en dexia · ἐν δεξιᾷ', v: '1:3', s: '최고의 영예의 자리', d: '최고의 영예와 권능과 권위의 자리. 왕의 존엄과 하나님과 동등한 지위를 상징합니다.' },
      name: { t: '이름', g: 'onoma · ὄνομα', v: '1:4', s: '“아들”이라는 칭호', d: '칭호. 예수님이 기업으로 얻으신 이름은 “아들”이며, 어떤 천사도 받지 못한 이름입니다.' } } },
  chips: [
    { id: 'col', tag: 'NT', en: 'Col 1:16–17', ko: '골 1:16–17', ten: 'For by him all things were created, in heaven and on earth, visible and invisible… all things were created through him and for him. And he is before all things, and in him all things hold together.', tko: '만물이 그에게 창조되되 하늘과 땅에서 보이는 것들과 보이지 않는 것들과… 만물이 다 그로 말미암고 그를 위하여 창조되었고 또한 그가 만물보다 먼저 계시고 만물이 그 안에 함께 섰느니라', wen: 'Paul says what Hebrews 1:2 says: creation came to be through the Son.', wko: '바울도 히브리서 1:2과 같은 고백을 합니다. 창조는 아들로 말미암아 이루어졌습니다.' },
    { id: 'john', tag: 'NT', en: 'John 1:1–3', ko: '요 1:1–3', ten: 'In the beginning was the Word, and the Word was with God, and the Word was God. He was in the beginning with God. All things were made through him, and without him was not any thing made that was made.', tko: '태초에 말씀이 계시니라 이 말씀이 하나님과 함께 계셨으니 이 말씀은 곧 하나님이시니라 그가 태초에 하나님과 함께 계셨고 만물이 그로 말미암아 지은 바 되었으니 지은 것이 하나도 그가 없이는 된 것이 없느니라', wen: 'An echo of Genesis 1, where the Triune God creates. The Word who speaks creation into being is the Son.', wko: '삼위 하나님이 창조하시는 창세기 1장의 메아리입니다. 창조를 말씀하신 그 말씀이 곧 아들이십니다.' },
    { id: 'jer', tag: 'OT', en: 'Jer 31:33', ko: '렘 31:33', ten: 'I will put my law within them, and I will write it on their hearts. And I will be their God, and they shall be my people.', tko: '내가 나의 법을 그들의 속에 두며 그 마음에 기록하여 나는 그들의 하나님이 되고 그들은 내 백성이 되리라', wen: 'From stone tablets to hearts. The old is fulfilled, not thrown away.', wko: '돌판에서 마음으로. 옛것은 폐기되는 것이 아니라 완성됩니다.' },
    { id: 'ps110a', tag: 'OT', en: 'Ps 110:1', ko: '시 110:1', ten: 'The LORD says to my Lord: “Sit at my right hand, until I make your enemies your footstool.”', tko: '여호와께서 내 주에게 말씀하시기를 내가 네 원수로 네 발등상 되게 하기까지 너는 내 우편에 앉으라 하셨도다', wen: 'Behind “he sat down at the right hand”. Hebrews returns to it in verse 13.', wko: '“우편에 앉으셨느니라”의 배경입니다. 히브리서는 13절에서 다시 인용합니다.' }] },

{ id: 'm2', num: 'II', range: '5–6', scene: 'angels', art: '3D · R3F — one central light; a wide arc of small lights lowers and dims toward it.',
  en: { title: 'The Son vs the angels', quote: '“Let all God’s angels worship him.”', sref: 'Hebrews 1:6', cap: 'Scene: many small lights bow in a wide arc beneath one central light.',
    snips: ['“You are my Son, today I have begotten you”', '“Let all God’s angels worship him”'],
    verses: [
      [5, 'For to which of the angels did God ever say, “You are my Son, today I have [begotten|begotten] you”? Or again, “I will be to him a father, and he shall be to me a son”?'],
      [6, 'And again, when he brings the [firstborn|firstborn] into the [world|world], he says, “Let all God’s angels [worship|worship] him.”']],
    com: [['h', 'A coronation word'],
      ['p', 'Psalm 2 pictures the kings of the earth rebelling against God. God answers by setting his Son over all. Everything will submit to him, those who defy him face the consequences, and those who take refuge in him find joy. “You are my Son” is spoken at a coronation. God never said it to an angel.'],
      ['h', 'A father’s promise'],
      ['p', 'In 2 Samuel 7 God promises David an eternal kingdom through his line, a promise that reaches all the way to Jesus Christ. David answers with a prayer, understanding that a Greater One would come to fulfil it.'],
      ['h', 'Firstborn, and worshipped'],
      ['p', '“Firstborn” is about rank, not birth order: the one with the right of inheritance. When he enters the world, the angels are commanded to worship him. The Hebrew text of Deuteronomy 32:43 leaves out the angels, but the Greek Septuagint includes them. This is Moses’ last song to Israel. Some 1,200–1,400 years before Jesus, it looks ahead to a greater Rock who will avenge his children, make atonement for his land and people, and be worshipped by angels.']] },
  ko: { title: '아들과 천사들', quote: '“하나님의 모든 천사가 저에게 경배할지어다”', sref: '히브리서 1:6', cap: '장면: 작은 빛들이 한 중심 빛 아래 넓은 호를 그리며 엎드립니다.',
    snips: ['네가 내 아들이라 오늘날 내가 너를 낳았다', '하나님의 모든 천사가 저에게 경배할지어다'],
    verses: [
      [5, '하나님이 어느 때에 천사 중 누구에게 네가 내 아들이라 오늘날 내가 너를 [begotten|낳았다] 하셨으며 또 다시 나는 그에게 아버지가 되고 그는 내게 아들이 되리라 하셨느뇨'],
      [6, '또 [firstborn|맏아들]을 이끌어 [world|세상]에 다시 들어오게 하실 때에 하나님의 모든 천사가 저에게 [worship|경배]할지어다 말씀하시며']],
    com: [['h', '대관식의 말씀'],
      ['p', '시편 2편은 세상의 왕들이 하나님을 대적하는 모습을 그립니다. 하나님은 아들을 만물 위에 세우심으로 답하십니다. 모든 것이 그에게 복종하고, 그를 거역하는 자는 대가를 치르며, 그에게 피하는 자는 기쁨을 얻습니다. “너는 내 아들이라”는 대관식의 말씀입니다. 하나님은 이 말씀을 어떤 천사에게도 하지 않으셨습니다.'],
      ['h', '아버지의 약속'],
      ['p', '사무엘하 7장에서 하나님은 다윗의 혈통을 통해 영원한 나라를 약속하십니다. 이 약속은 예수 그리스도께까지 이어집니다. 다윗은 더 크신 분이 오셔서 이 약속을 이루실 것을 깨닫고 기도로 응답합니다.'],
      ['h', '맏아들, 경배받으시는 분'],
      ['p', '“맏아들”은 출생 순서가 아니라 지위, 곧 기업을 이을 권리를 가진 자를 뜻합니다. 그가 세상에 들어오실 때 천사들은 그에게 경배하라는 명령을 받습니다. 신명기 32:43의 히브리어 본문에는 천사가 없지만, 헬라어 칠십인역에는 이 명령이 들어 있습니다. 이는 모세가 죽기 전 이스라엘에게 부른 마지막 노래입니다. 예수님보다 1,200–1,400년 앞서, 자녀의 피를 갚으시고 땅과 백성을 위해 속죄하시며 천사들에게 경배받으실 더 크신 반석을 내다봅니다.']] },
  words: {
    en: {
      begotten: { t: 'Begotten', g: 'gegennēka · γεγέννηκα', v: '1:5', s: 'Fathered, brought into being', d: 'To be fathered, produced, brought into existence; to generate offspring.' },
      firstborn: { t: 'Firstborn', g: 'prōtotokos · πρωτότοκος', v: '1:6', s: 'Rank, not birth order', d: 'Mainly about position or rank, not time or birth order. The firstborn is the one with the right of inheritance.' },
      world: { t: 'World', g: 'oikoumenē · οἰκουμένη', v: '1:6', s: 'The whole inhabited earth', d: 'The whole inhabited earth: its peoples and inhabitants.' },
      worship: { t: 'Worship', g: 'proskynēsatōsan · προσκυνησάτωσαν', v: '1:6', s: 'To revere, adore, bow down', d: 'To revere, to adore, to show deep respect. To bow down before him.' } },
    ko: {
      begotten: { t: '낳았다', g: 'gegennēka · γεγέννηκα', v: '1:5', s: '아버지가 되어 낳음', d: '아버지가 되어 낳다, 존재하게 하다, 자손을 낳다.' },
      firstborn: { t: '맏아들', g: 'prōtotokos · πρωτότοκος', v: '1:6', s: '순서가 아니라 지위', d: '시간 순서와 상관없는 지위나 계급을 주로 뜻합니다. 기업을 이을 권리를 가진 자입니다.' },
      world: { t: '세상', g: 'oikoumenē · οἰκουμένη', v: '1:6', s: '사람이 사는 온 땅', d: '사람이 사는 온 땅, 곧 땅 위의 모든 사람.' },
      worship: { t: '경배', g: 'proskynēsatōsan · προσκυνησάτωσαν', v: '1:6', s: '공경하고 엎드림', d: '공경하고 흠모하며 존경을 표하는 것. 그 앞에 엎드려 절함.' } } },
  chips: [
    { id: 'ps2', tag: 'OT', en: 'Ps 2:7', ko: '시 2:7', ten: 'I will tell of the decree: The LORD said to me, “You are my Son; today I have begotten you.”', tko: '내가 영을 전하노라 여호와께서 내게 이르시되 너는 내 아들이라 오늘날 내가 너를 낳았도다', wen: 'The kings of the earth rebel; God sets his Son over all. Those who take refuge in him find joy.', wko: '세상 왕들이 대적하나 하나님은 아들을 만물 위에 세우십니다. 그에게 피하는 자는 복이 있습니다.' },
    { id: 'sam', tag: 'OT', en: '2 Sam 7:14', ko: '삼하 7:14', ten: 'I will be to him a father, and he shall be to me a son.', tko: '나는 그 아비가 되고 그는 내 아들이 되리니', wen: 'God promises David an eternal kingdom through his line, reaching to Jesus Christ.', wko: '다윗의 혈통을 통한 영원한 나라의 약속, 예수 그리스도께까지 이어집니다.' },
    { id: 'chr', tag: 'OT', en: '1 Chr 17:13', ko: '대상 17:13', ten: 'I will be to him a father, and he shall be to me a son. I will not take my steadfast love from him…', tko: '나는 그 아비가 되고 그는 내 아들이 되리니 나의 자비를 저에게서 빼앗지 아니하기를…', wen: 'The same promise, retold in Chronicles.', wko: '역대기에 다시 기록된 같은 약속입니다.' },
    { id: 'deut', tag: 'OT', en: 'Deut 32:43', ko: '신 32:43', ten: 'Rejoice with him, O heavens; bow down to him, all gods, for he avenges the blood of his children and takes vengeance on his adversaries.', tko: '너희 열방은 그 백성과 즐거워하라 주께서 그 종들의 피를 갚으사 그 대적들에게 복수하시고 자기 땅과 자기 백성을 위하여 속죄하시리로다', wen: 'Moses’ last song. The Hebrew text omits the angels; the Greek Septuagint, which Hebrews quotes, includes them.', wko: '모세의 마지막 노래. 히브리어 본문에는 천사가 없지만, 히브리서가 인용한 칠십인역에는 들어 있습니다.' }] },

{ id: 'm3', num: 'III', range: '7–9', scene: 'throne', art: '3D · R3F — ember flames gust like wind on the left; a still pillar of gold light (the throne) on the right.',
  en: { title: 'Servants vs the throne', quote: '“Your throne, O God, is forever and ever.”', sref: 'Hebrews 1:8', cap: 'Scene: flames flicker and move like wind; beside them a throne of light stands still.',
    snips: ['“He makes his angels winds, and his ministers a flame of fire”', '“Your throne, O God, is forever and ever”', '…anointed you with the oil of gladness'],
    verses: [
      [7, 'Of the angels he says, “He makes his angels [winds|winds], and his [ministers|ministers] a [flame|flame of fire].”'],
      [8, 'But of the Son he says, “Your throne, O God, is forever and ever, the [scepter|scepter] of uprightness is the scepter of your kingdom.'],
      [9, 'You have loved righteousness and hated wickedness; therefore God, your God, has anointed you with the [oil|oil of gladness] beyond your companions.”']],
    com: [['h', 'Wind and fire'],
      ['p', 'Of the angels, God says he makes them winds and flames of fire. They work invisibly, swiftly and powerfully, with holy fervour. But Psalm 104 makes a point of calling them ministers: servants of God, nothing more.'],
      ['h', 'A throne forever'],
      ['p', 'Psalm 45 was a royal wedding song, sung when an Israelite king married a foreign princess. Hebrews reads it as a prophecy of the Messiah. His throne is God’s throne and lasts forever. His scepter of uprightness means perfect moral authority and fair rule: an eternal kingdom built on righteousness.'],
      ['h', 'Loved righteousness, hated wickedness'],
      ['p', 'This describes Jesus’ sinless life and perfect obedience. He did not avoid sin out of duty; he truly hated evil and loved good. So God anointed him with the oil of gladness. Pouring oil was a sign of celebration, of honouring a guest, or of setting a leader apart for a holy task. Because of his obedience and his victory over sin and death, God gave Jesus the highest place of joy and honour in heaven: the final triumph of good over evil.']] },
  ko: { title: '종들과 보좌', quote: '“하나님이여 주의 보좌가 영영하며”', sref: '히브리서 1:8', cap: '장면: 불꽃은 바람처럼 흔들리고, 그 곁에 빛의 보좌가 흔들림 없이 서 있습니다.',
    snips: ['그의 천사들을 바람으로, 사역자들을 불꽃으로', '하나님이여 주의 보좌가 영영하며', '즐거움의 기름을 네게 부어'],
    verses: [
      [7, '또 천사들에게 관하여는 그는 그의 천사들을 [winds|바람]으로, 그의 [ministers|사역자들]을 [flame|불꽃]으로 삼으시느니라 하셨으되'],
      [8, '아들에게 관하여는 하나님이여 주의 보좌가 영영하며 주의 나라의 [scepter|홀]은 공평한 홀이니이다'],
      [9, '네가 의를 사랑하고 불법을 미워하였으니 그러므로 하나님 곧 너의 하나님이 [oil|즐거움의 기름]을 네게 부어 네 동류들보다 승하게 하셨도다 하였고']],
    com: [['h', '바람과 불꽃'],
      ['p', '하나님은 천사들을 바람과 불꽃으로 삼으신다고 말씀하십니다. 그들은 보이지 않게, 빠르고 강력하게, 거룩한 열심으로 일합니다. 그러나 시편 104편은 그들을 굳이 “사역자”라고 부릅니다. 하나님의 종일 뿐, 그 이상은 아닙니다.'],
      ['h', '영원한 보좌'],
      ['p', '시편 45편은 이스라엘 왕이 이방 공주와 혼인할 때 부른 왕실 혼인 노래입니다. 히브리서는 이를 메시아에 관한 예언으로 읽습니다. 그분의 보좌는 하나님의 보좌이며 영원합니다. 공평한 홀은 완전한 도덕적 권위와 공정한 다스림, 곧 의 위에 세워진 영원한 나라를 뜻합니다.'],
      ['h', '의를 사랑하고 불법을 미워하심'],
      ['p', '이는 예수님의 죄 없는 삶과 완전한 순종을 보여 줍니다. 그분은 의무감으로 죄를 피하신 것이 아니라, 진심으로 악을 미워하고 선을 사랑하셨습니다. 그래서 하나님은 즐거움의 기름을 그에게 부으셨습니다. 기름을 붓는 것은 축하, 손님을 높임, 거룩한 일을 위해 지도자를 구별함의 상징이었습니다. 예수님의 순종과 죄와 죽음에 대한 승리로 인해, 하나님은 그분께 하늘에서 최고의 기쁨과 영예의 자리를 주셨습니다. 선이 악을 이기는 궁극적 승리입니다.']] },
  words: {
    en: {
      winds: { t: 'Winds', g: 'pneumata · πνεύματα', v: '1:7', s: 'Invisible, swift, powerful', d: 'Angels are described as wind: invisibly swift and powerful.' },
      ministers: { t: 'Ministers', g: 'leitourgous · λειτουργούς', v: '1:7', s: 'Servants, nothing more', d: 'Also means angels, but the psalm stresses they are only ministers of God, nothing more.' },
      flame: { t: 'Flame of fire', g: 'phloga pyros · φλόγα πυρός', v: '1:7', s: 'Fiery devotion', d: 'Fiery devotion and all-consuming fervour: a very strong, intense passion.' },
      scepter: { t: 'Scepter', g: 'rhabdos · ῥάβδος', v: '1:8', s: 'Badge of royal authority', d: 'A rod or staff. Here, the ruler’s staff: badge of royalty and emblem of authority and power.' },
      oil: { t: 'Oil of gladness', g: 'elaion agalliaseōs · ἔλαιον ἀγαλλιάσεως', v: '1:9', s: 'Royal anointing of joy', d: 'Perfumed oil poured on the head with joy and rejoicing. A royal anointing of supreme joy, divine favour and eternal celebration, given for his perfect righteousness.' } },
    ko: {
      winds: { t: '바람', g: 'pneumata · πνεύματα', v: '1:7', s: '보이지 않고 빠르며 강함', d: '천사들을 바람으로 묘사합니다. 바람처럼 보이지 않게, 빠르고 강력하게 일합니다.' },
      ministers: { t: '사역자들', g: 'leitourgous · λειτουργούς', v: '1:7', s: '종일 뿐', d: '천사들을 가리킵니다. 시편은 그들이 하나님의 사역자일 뿐, 그 이상이 아님을 강조합니다.' },
      flame: { t: '불꽃', g: 'phloga pyros · φλόγα πυρός', v: '1:7', s: '불타는 헌신', d: '불타는 헌신과 모든 것을 삼키는 열심. 매우 강렬한 열정.' },
      scepter: { t: '홀', g: 'rhabdos · ῥάβδος', v: '1:8', s: '왕권의 표', d: '막대기나 지팡이. 여기서는 통치자의 지팡이로, 왕권의 표이자 권위와 능력의 상징입니다.' },
      oil: { t: '즐거움의 기름', g: 'elaion agalliaseōs · ἔλαιον ἀγαλλιάσεως', v: '1:9', s: '기쁨의 왕적 기름부음', d: '머리에 붓는 향기로운 기름으로 기쁨과 즐거움의 표현. 완전한 의로 인해 주어진 최고의 기쁨, 신적 은총, 영원한 축하의 왕적 기름부음입니다.' } } },
  chips: [
    { id: 'ps104', tag: 'OT', en: 'Ps 104:4', ko: '시 104:4', ten: 'He makes his messengers winds, his ministers a flaming fire.', tko: '바람으로 자기 사자를 삼으시며 화염으로 자기 사역자를 삼으시며', wen: 'A creation psalm: angels as winds and fire, but still only ministers.', wko: '창조의 시편. 천사는 바람과 불꽃 같으나 여전히 사역자일 뿐입니다.' },
    { id: 'ps45', tag: 'OT', en: 'Ps 45:6–7', ko: '시 45:6–7', ten: 'Your throne, O God, is forever and ever. The scepter of your kingdom is a scepter of uprightness; you have loved righteousness and hated wickedness. Therefore God, your God, has anointed you with the oil of gladness beyond your companions.', tko: '하나님이여 주의 보좌가 영영하며 주의 나라의 홀은 공평한 홀이니이다 왕이 정의를 사랑하고 악을 미워하시므로 그러므로 하나님 곧 왕의 하나님이 즐거움의 기름으로 왕에게 부어 왕의 동류보다 승하게 하셨나이다', wen: 'A royal wedding song that Hebrews reads as a prophecy of the Messiah’s eternal throne.', wko: '히브리서가 메시아의 영원한 보좌에 관한 예언으로 읽는 왕실 혼인 노래입니다.' }] },

{ id: 'm4', num: 'IV', range: '10–12', scene: 'fold', art: '3D · R3F — star-cloth mesh folds and rolls up like a robe; the centre light is fixed and never moves.',
  en: { title: 'The heavens perish, you remain', quote: '“They will perish, but you remain.”', sref: 'Hebrews 1:11 · Psalm 102:25–27', cap: 'Scene: the heavens fold and wear out like an old garment, while one light holds perfectly still.',
    snips: ['“You, Lord, laid the foundation of the earth”', '“They will perish, but you remain”', '“Like a robe you will roll them up”'],
    verses: [
      [10, 'And, “You, Lord, laid the foundation of the earth in the beginning, and the heavens are the work of your hands;'],
      [11, 'they will [perish|perish], but you [remain|remain]; they will all wear out like a garment,'],
      [12, 'like a [robe|robe you will roll them up], like a garment they will be changed. But you are [same|the same], and your years will have no end.”']],
    com: [['h', 'A prayer from affliction'],
      ['p', 'Psalm 102 is titled “A prayer of one afflicted, when he is faint and pours out his complaint before the LORD.” David did not write it, and its author is unknown. Some verses hint at the Babylonian captivity. Yet the psalmist finds peace by anchoring himself to the unchanging, eternal nature of God, who has a plan to restore Israel.'],
      ['h', 'Wearing out like a garment'],
      ['p', 'The created world, earth and heavens alike, is not eternal. It is wearing out, like a garment after long use. The universe is decaying and fraying away.'],
      ['h', 'Rolled up like a robe'],
      ['p', '“Like a robe you will roll them up” shows how easily the Son can replace this world, the way you change a piece of clothing. The heavens fold; he does not. “You are the same, and your years will have no end.” Jesus Christ remains the same as ever, untouched by decay.']] },
  ko: { title: '하늘은 없어지나 주는 영존하심', quote: '“그것들은 멸망할 것이나 오직 주는 영존할 것이요”', sref: '히브리서 1:11 · 시편 102:25–27', cap: '장면: 하늘이 낡은 옷처럼 접히고 해어지지만, 한 빛은 조금도 움직이지 않습니다.',
    snips: ['태초에 주께서 땅의 기초를 두셨으며', '그것들은 멸망할 것이나 오직 주는 영존할 것이요', '의복처럼 갈아 입을 것이요'],
    verses: [
      [10, '또 주여 태초에 주께서 땅의 기초를 두셨으며 하늘도 주의 손으로 지으신 바라'],
      [11, '그것들은 [perish|멸망]할 것이나 오직 주는 [remain|영존]할 것이요 그것들은 다 옷과 같이 낡아지리니'],
      [12, '[robe|의복처럼 갈아 입을] 것이요 그것들이 옷과 같이 변할 것이나 주는 [same|여전하여] 연대가 다함이 없으리라 하였으나']],
    com: [['h', '고난 중의 기도'],
      ['p', '시편 102편의 제목은 “곤고한 자가 마음이 상하여 그 근심을 여호와 앞에 토로하는 기도”입니다. 다윗이 쓴 것이 아니며 저자는 알려져 있지 않습니다. 어떤 구절들은 바벨론 포로기를 암시합니다. 그러나 시인은 이스라엘을 회복하실 계획을 가지신, 변하지 않는 영원하신 하나님께 닻을 내림으로 평안을 얻습니다.'],
      ['h', '옷과 같이 낡아짐'],
      ['p', '땅과 하늘, 곧 창조된 세상은 영원하지 않습니다. 오래 입은 옷처럼 낡아 가고 있습니다. 우주는 쇠하고 해어져 가고 있습니다.'],
      ['h', '의복처럼 갈아입히심'],
      ['p', '“의복처럼 갈아 입을 것이요”라는 말씀은 아들이 이 세상을 옷을 갈아입듯 손쉽게 바꾸실 수 있음을 보여 줍니다. 하늘은 접히지만 그분은 그렇지 않습니다. “주는 여전하여 연대가 다함이 없으리라.” 예수 그리스도는 쇠함에 영향받지 않고 언제나 같으십니다.']] },
  words: {
    en: {
      perish: { t: 'Perish', g: 'apolountai · ἀπολοῦνται', v: '1:11', s: 'To vanish away', d: 'To be blotted out, to vanish away.' },
      remain: { t: 'Remain', g: 'diameneis · διαμένεις', v: '1:11', s: 'To stay permanently', d: 'To stay permanently; to remain and continue.' },
      robe: { t: 'Rolled up like a robe', g: 'peribolaion · περιβόλαιον', v: '1:12', s: 'Changed like clothing', d: 'The Son can replace the present world as easily as changing a piece of clothing.' },
      same: { t: 'The same', g: 'ho autos · ὁ αὐτός', v: '1:12', s: 'Untouched by decay', d: 'The universe decays and frays away; Jesus Christ remains the same as ever.' } },
    ko: {
      perish: { t: '멸망', g: 'apolountai · ἀπολοῦνται', v: '1:11', s: '사라져 없어짐', d: '지워지다, 사라져 없어지다.' },
      remain: { t: '영존', g: 'diameneis · διαμένεις', v: '1:11', s: '영원히 머묾', d: '영원히 머물다, 계속 존재하다.' },
      robe: { t: '의복처럼 갈아 입음', g: 'peribolaion · περιβόλαιον', v: '1:12', s: '옷처럼 바꾸심', d: '아들은 옷을 갈아입듯 지금의 세상을 손쉽게 바꾸실 수 있습니다.' },
      same: { t: '여전하심', g: 'ho autos · ὁ αὐτός', v: '1:12', s: '쇠하지 않으심', d: '우주는 쇠하고 해어지지만, 예수 그리스도는 언제나 같으십니다.' } } },
  chips: [
    { id: 'ps102', tag: 'OT', en: 'Ps 102:25–27', ko: '시 102:25–27', ten: 'Of old you laid the foundation of the earth, and the heavens are the work of your hands. They will perish, but you will remain; they will all wear out like a garment. You will change them like a robe, and they will pass away, but you are the same, and your years have no end.', tko: '주께서 옛적에 땅의 기초를 두셨사오며 하늘도 주의 손으로 지으신 바니이다 천지는 없어지려니와 주는 영존하시겠고 그것들은 다 옷 같이 낡으리니 의복 같이 바꾸시면 바뀌려니와 주는 여상하시고 주의 연대는 무궁하리이다', wen: 'A lament from affliction, anchored in God’s unchanging nature.', wko: '고난 중의 탄식이, 변하지 않는 하나님의 본성에 닻을 내립니다.' }] },

{ id: 'm5', num: 'V', range: '13–14', scene: 'exalted', art: '3D · R3F — one light rises to the highest point; a gold horizon settles beneath it with dim shapes below.',
  en: { title: 'Sit at my right hand', quote: '“Sit at my right hand until I make your enemies a footstool for your feet.”', sref: 'Hebrews 1:13 · Psalm 110:1', cap: 'Scene: one light rises to the highest place; everything else settles beneath it.',
    snips: ['“Sit at my right hand until I make your enemies a footstool”', 'Ministering spirits sent out to serve'],
    verses: [
      [13, 'And to which of the angels has he ever said, “Sit at my [right|right hand] until I make your enemies a [footstool|footstool] for your feet”?'],
      [14, 'Are they not all [spirits|ministering spirits] sent out to serve for the sake of those who are to [heirs|inherit salvation]?']],
    com: [['h', 'The Lord says to my Lord'],
      ['p', 'In Psalm 110:1 David writes, “The LORD says to my Lord.” That is Yahweh speaking to David’s Adonai (lord, owner, ruler). David was king of Israel and held the highest authority, so in human terms he had no Adonai. The one greater than David can only be the Messiah, Jesus.'],
      ['h', 'A footstool for your feet'],
      ['p', 'Kings who conquered lands would literally place their feet on the necks of defeated enemies, a sign of total dominance. The Son is seated, and every enemy will be placed beneath him.'],
      ['h', 'Servants and the Son'],
      ['p', 'So the chapter closes where it began. Angels are ministering spirits, servants and messengers sent to care for those who will inherit salvation. Jesus is God’s Son, the exact nature and likeness of God himself, through whom and for whom the world was created.']] },
  ko: { title: '내 우편에 앉으라', quote: '“네 원수로 네 발등상 되게 할 때까지 내 우편에 앉았으라”', sref: '히브리서 1:13 · 시편 110:1', cap: '장면: 한 빛이 가장 높은 자리에 오르고, 다른 모든 것은 그 아래에 놓입니다.',
    snips: ['네 원수로 네 발등상 되게 할 때까지 내 우편에 앉았으라', '구원 얻을 후사들을 위하여 섬기라고'],
    verses: [
      [13, '어느 때에 천사 중 누구에게 네 원수로 네 [footstool|발등상] 되게 할 때까지 내 [right|우편]에 앉았으라 하셨느뇨'],
      [14, '모든 천사들은 [spirits|부리는 영]으로서 [heirs|구원 얻을 후사들]을 위하여 섬기라고 보내심이 아니뇨']],
    com: [['h', '여호와께서 내 주에게'],
      ['p', '시편 110:1에서 다윗은 “여호와께서 내 주에게 말씀하시기를”이라고 씁니다. 이는 여호와께서 다윗의 아도나이(주, 주인, 통치자)에게 말씀하시는 것입니다. 다윗은 이스라엘의 왕으로 최고의 권위를 가졌기에, 사람의 관점에서 그에게는 아도나이가 없었습니다. 다윗보다 더 높으신 분은 메시아 예수님밖에 없습니다.'],
      ['h', '네 발등상'],
      ['p', '땅을 정복한 왕들은 패배한 원수의 목에 실제로 발을 올려놓았습니다. 완전한 지배의 표시입니다. 아들은 앉으셨고, 모든 원수가 그분의 발아래 놓일 것입니다.'],
      ['h', '종들과 아들'],
      ['p', '이 장은 시작한 곳에서 끝납니다. 천사들은 구원 얻을 후사들을 섬기도록 보내심을 받은 부리는 영, 곧 종이자 사자입니다. 예수님은 하나님의 아들이시며, 하나님 본체의 정확한 형상이시고, 세상이 그분으로 말미암아, 그분을 위하여 창조되었습니다.']] },
  words: {
    en: {
      right: { t: 'My right hand', g: 'ek dexiōn · ἐκ δεξιῶν', v: '1:13', s: 'Named already in v3', d: 'Also named in verse 3: the highest place of honour, power and authority.' },
      footstool: { t: 'Footstool', g: 'hypopodion · ὑποπόδιον', v: '1:13', s: 'Total dominance', d: 'Conquering kings placed their feet on the necks of defeated enemies, a symbol of total dominance.' },
      spirits: { t: 'Ministering spirits', g: 'leitourgika pneumata · λειτουργικὰ πνεύματα', v: '1:14', s: 'Servants sent to care', d: 'Angels are only servants: spirits sent to care for people who will inherit salvation (NLT).' },
      heirs: { t: 'Inherit salvation', g: 'klēronomein sōtērian · κληρονομεῖν σωτηρίαν', v: '1:14', s: 'Salvation as our share', d: 'Those who receive salvation as their allotted share, by right of being children of God.' } },
    ko: {
      right: { t: '우편', g: 'ek dexiōn · ἐκ δεξιῶν', v: '1:13', s: '3절에도 나옴', d: '3절에서도 언급된, 최고의 영예와 권능과 권위의 자리입니다.' },
      footstool: { t: '발등상', g: 'hypopodion · ὑποπόδιον', v: '1:13', s: '완전한 지배', d: '정복한 왕들은 패배한 원수의 목에 발을 올려놓았습니다. 완전한 지배의 상징입니다.' },
      spirits: { t: '부리는 영', g: 'leitourgika pneumata · λειτουργικὰ πνεύματα', v: '1:14', s: '돌보도록 보내진 종', d: '천사들은 종일 뿐입니다. 구원을 상속할 사람들을 돌보도록 보내진 영들입니다(NLT).' },
      heirs: { t: '구원 얻을 후사들', g: 'klēronomein sōtērian · κληρονομεῖν σωτηρίαν', v: '1:14', s: '구원을 기업으로 받음', d: '하나님의 자녀 된 권리로 구원을 자기 몫의 기업으로 받는 사람들.' } } },
  chips: [
    { id: 'ps110', tag: 'OT', en: 'Ps 110:1', ko: '시 110:1', ten: 'The LORD says to my Lord: “Sit at my right hand, until I make your enemies your footstool.”', tko: '여호와께서 내 주에게 말씀하시기를 내가 네 원수로 네 발등상 되게 하기까지 너는 내 우편에 앉으라 하셨도다', wen: 'Yahweh speaks to David’s Adonai. As king, David had no human lord above him, so this points to the Messiah.', wko: '여호와께서 다윗의 주(아도나이)께 말씀하십니다. 왕인 다윗에게는 사람 주인이 없었으니, 이는 메시아를 가리킵니다.' },
    { id: 'heb3', tag: 'NT', en: 'Heb 1:3', ko: '히 1:3', ten: 'After making purification for sins, he sat down at the right hand of the Majesty on high.', tko: '죄를 정결케 하는 일을 하시고 높은 곳에 계신 위엄의 우편에 앉으셨느니라', wen: 'The chapter closes where verse 3 began: the Son, seated.', wko: '이 장은 3절이 시작한 곳, 곧 앉으신 아들로 마무리됩니다.' }] }
];

const SUM: Record<Lang, Summary> = {
  en: { groups: [
      { h: 'What the author says about Jesus', items: [['v2', 'Heir of all things, through whom God created the world.'], ['v3', 'God himself, seated at the right hand of God.'], ['v4', 'Far superior to the angels, with a name far more excellent than theirs.']] },
      { h: 'What God said about Jesus', items: [['v5', 'He calls Jesus his very own Son (Ps 2:7; 2 Sam 7:14; 1 Chr 17:13).'], ['v6', 'All the angels will worship him.'], ['vv8–9', 'Anointed with the oil of joy; an eternal kingdom built on righteousness.'], ['vv10–12', 'Earth and heaven slowly decay; he remains the same, and rolls them up like a garment.'], ['v13', 'Total dominance over everything.']] },
      { h: 'What God said about angels', items: [['v7', 'Like winds and flames of fire: they work invisibly but swiftly, powerfully and with holy fervour.'], ['v14', 'Ministering spirits, sent to serve those who will inherit salvation.']] }],
    intentH: 'The author’s intention', intentShort: 'To prove that Jesus Christ is far greater than angels. Many Jewish readers held angels very high; some saw Jesus as a high-ranking angel. The author separates the servants from the King.',
    intent: ['To prove that Jesus Christ is far greater than angels or any spiritual being.', 'Jewish people held angels very high, believing the Law of Moses was delivered through angelic mediators at Mount Sinai. Some viewed Jesus as a high-ranking angel; some worshipped angels.', 'The author draws a clear line: angels are servants, created beings and worshippers of the King. Jesus Christ is the Creator and the Sovereign.'] },
  ko: { groups: [
      { h: '저자가 예수님에 대해 말하는 것', items: [['2절', '만유의 후사이시며, 하나님께서 그로 말미암아 세상을 지으셨습니다.'], ['3절', '하나님 자신이시며, 하나님 우편에 앉으셨습니다.'], ['4절', '천사보다 훨씬 뛰어나시며, 더 아름다운 이름을 얻으셨습니다.']] },
      { h: '하나님이 예수님에 대해 하신 말씀', items: [['5절', '예수님을 친아들이라 부르십니다(시 2:7, 삼하 7:14, 대상 17:13).'], ['6절', '모든 천사가 그에게 경배할 것입니다.'], ['8–9절', '즐거움의 기름부음을 받으시고, 의 위에 영원한 나라를 세우십니다.'], ['10–12절', '땅과 하늘은 쇠하지만 그분은 여전하시며, 옷처럼 그것들을 말아 바꾸십니다.'], ['13절', '만물에 대한 완전한 주권.']] },
      { h: '하나님이 천사에 대해 하신 말씀', items: [['7절', '바람과 불꽃 같아서, 보이지 않게 그러나 빠르고 강력하게, 거룩한 열심으로 일합니다.'], ['14절', '구원 얻을 후사들을 섬기도록 보내심을 받은 부리는 영입니다.']] }],
    intentH: '저자의 의도', intentShort: '예수 그리스도가 천사보다 훨씬 뛰어나심을 증명하는 것. 유대인들은 천사를 매우 높였고, 어떤 이들은 예수님을 높은 천사로 여겼습니다. 저자는 종들과 왕을 분명히 구분합니다.',
    intent: ['예수 그리스도가 천사나 어떤 영적 존재보다 훨씬 뛰어나심을 증명하는 것.', '유대인들은 모세의 율법이 시내산에서 천사들을 통해 전해졌다고 믿었기에 천사를 매우 높였습니다. 어떤 이들은 예수님을 높은 계급의 천사로 보았고, 어떤 이들은 천사를 숭배했습니다.', '저자는 분명한 선을 긋습니다. 천사는 종이며 피조물이고 왕께 경배하는 자들입니다. 예수 그리스도는 창조주이시며 주권자이십니다.'] }
};

export const chapter1: ChapterContent = { number: 1, movements: MV, summary: SUM };
