import type { ChapterContent, ChapterCopy, Lang, Movement, Summary } from "../types";

// Verse strings mark key words as [key|display text]; see content/parse.ts.
const MV: Movement[] = [
{ id: 'm1', num: 'I', range: '1–4', scene: 'drift', art: '3D · R3F — a small light tethered to a steady one by a gold thread; a current streams past and pulls it sideways, the thread thins, then draws it back.',
  en: { title: 'Do not drift away', quote: '“Therefore we must pay much closer attention to what we have heard, lest we drift away from it.”', sref: 'Hebrews 2:1', cap: 'Scene: a small light is held to a steady one by a thin thread while the current pulls at it. Let go, and it drifts.',
    snips: ['We must pay much closer attention to what we have heard', 'The message declared by angels proved to be reliable', 'How shall we escape if we neglect such a great salvation?', 'God also bore witness by signs and wonders'],
    verses: [
      [1, 'Therefore we must [attention|pay much closer attention] to what we have heard, lest we [drift|drift away] from it.'],
      [2, 'For since the message declared by angels proved to be reliable, and every transgression or disobedience received a just retribution,'],
      [3, 'how shall we escape if we [neglect|neglect] such a great salvation? It was declared at first by the Lord, and it was attested to us by those who heard,'],
      [4, 'while God also [witness|bore witness] by [signs|signs] and [wonders|wonders] and various [miracles|miracles] and by [gifts|gifts of the Holy Spirit] distributed according to his will.']],
    com: [['h', 'Hold on, or drift'],
      ['p', 'Chapter 2 opens with “therefore”. Everything chapter 1 said about the Son, the radiance of God’s glory, heir and maker, seated far above the angels, now becomes a reason to listen. “Pay much closer attention” means beyond measure, exceedingly. “Drift away” pictures something slipping away from its hearers, like a boat carried off by the current. Nobody drifts on purpose. It happens slowly, to people who stop paying attention.'],
      ['p', 'What have they heard? Hebrews 1:1–2 answers: in the past God spoke through the prophets in many ways, but now he has spoken by his Son. That good news of salvation was announced first by Jesus himself, then passed on by the witnesses who heard him: the apostles and disciples.'],
      ['h', 'If the angels’ word stood firm'],
      ['p', 'The “message declared by angels” was real, and it held. Every disobedience received a just penalty. In Genesis 19 two angels warned Lot to take his wife and daughters out of Sodom. As God judged the city with burning sulphur, Lot’s wife looked back and became a pillar of salt. In Luke 1 the angel Gabriel told the priest Zechariah that his wife Elizabeth, though both were very old, would bear a son, John the Baptist. Zechariah did not believe, and he was unable to speak until the day it happened.'],
      ['p', 'If the word of angels carried that weight, how much more the word of the Son? “Neglect” is not open rebellion. It means showing no concern, being careless. So the question stands: how shall we escape if we treat such a great salvation carelessly?'],
      ['h', 'God bore witness too'],
      ['p', 'Jesus declared the gospel in speech, and those who heard confirmed it. God himself joined in that testimony. Signs pointed beyond themselves to his power: water turned into wine, five loaves and two fish feeding thousands, Lazarus raised from the dead. Wonders startled and amazed: Jesus walking on the water, Ananias and Sapphira falling dead, the earthquake at the Philippian jail where the jailer trembled in awe.'],
      ['p', 'Miracles showed power no one else had: a man born blind given eyes that worked, demons cast out, a raging storm calmed. And the gifts of the Holy Spirit, such as those listed in 1 Corinthians 12, were given to believers as God willed, confirming the words of Jesus and the apostles.']] },
  ko: { title: '잘못된 길로 빠져들지 않도록', quote: '“그러므로 우리는 들은 바를 더욱 굳게 간직하여, 잘못된 길로 빠져드는 일이 없어야 마땅하겠습니다.”', sref: '히브리서 2:1', cap: '장면: 작은 빛이 가는 줄로 흔들림 없는 빛에 매여 있고, 물살이 그것을 옆으로 끌어당깁니다. 놓으면 떠내려갑니다.',
    snips: ['우리는 들은 바를 더욱 굳게 간직하여', '천사들을 통하여 하신 말씀이 효력을 내어', '이렇게도 귀중한 구원을 소홀히 하고서야', '하나님께서도 표징과 기이한 일과 여러 가지 기적을 보이시고'],
    verses: [
      [1, '그러므로 우리는 들은 바를 [attention|더욱 굳게 간직하여], [drift|잘못된 길로 빠져드는] 일이 없어야 마땅하겠습니다.'],
      [2, '천사들을 통하여 하신 말씀이 효력을 내어, 모든 범행과 불순종하는 행위가 공정한 갚음을 받았거든,'],
      [3, '하물며 우리가 이렇게도 귀중한 구원을 [neglect|소홀히 하고서야], 어떻게 그 갚음을 피할 수 있겠습니까? 이 구원은 주님께서 처음에 말씀하신 것이요, 그것을 들은 사람들이 우리에게 확증하여 준 것입니다.'],
      [4, '그리고 하나님께서도 [signs|표징]과 [wonders|기이한 일]과 여러 가지 [miracles|기적]을 보이시고, 또 자기의 뜻을 따라, [gifts|성령의 선물을 나누어주심]으로써, 그들과 함께 [witness|증언하여 주셨습니다].']],
    com: [['h', '붙들거나, 떠내려가거나'],
      ['p', '2장은 “그러므로”로 시작합니다. 1장이 아들에 대해 말한 모든 것, 곧 하나님의 영광의 광채이시며 만물의 상속자이자 창조자이시고 천사들보다 훨씬 높이 앉으신 분이라는 사실이 이제 귀 기울여야 할 이유가 됩니다. “더욱 굳게 간직하다”는 헤아릴 수 없이, 매우 크게 주의를 기울인다는 뜻입니다. “잘못된 길로 빠져들다”는 물살에 떠밀려 가는 배처럼 듣는 사람에게서 미끄러져 멀어지는 모습입니다. 일부러 떠내려가는 사람은 없습니다. 주의를 멈춘 사람에게 천천히 일어나는 일입니다.'],
      ['p', '그들이 들은 것은 무엇입니까? 히브리서 1:1–2가 답합니다. 옛날에는 하나님께서 예언자들을 통하여 여러 가지 방법으로 말씀하셨으나, 이제는 아들을 통하여 말씀하셨습니다. 그 구원의 기쁜 소식은 예수님께서 처음 친히 선포하셨고, 그분을 듣고 본 증인들, 곧 사도들과 제자들이 전해 주었습니다.'],
      ['h', '천사들의 말씀도 굳게 섰다면'],
      ['p', '“천사들을 통하여 하신 말씀”은 참되었고, 그대로 이루어졌습니다. 모든 불순종은 공정한 갚음을 받았습니다. 창세기 19장에서 두 천사가 롯에게 아내와 두 딸을 데리고 소돔을 떠나라고 경고합니다. 하나님께서 유황불로 그 성을 심판하실 때, 롯의 아내는 뒤를 돌아보다가 소금 기둥이 되었습니다. 누가복음 1장에서 천사 가브리엘은 제사장 사가랴에게, 둘 다 매우 늙었지만 아내 엘리사벳이 아들, 곧 세례자 요한을 낳을 것이라고 알립니다. 사가랴는 믿지 않았고, 그 일이 이루어지는 날까지 말을 하지 못하게 되었습니다.'],
      ['p', '천사들의 말씀이 그만큼 무거웠다면, 아들의 말씀은 얼마나 더하겠습니까? “소홀히 하다”는 드러내 놓고 거역하는 것이 아닙니다. 관심을 두지 않는 것, 부주의한 것입니다. 그래서 질문이 남습니다. 이렇게도 귀중한 구원을 소홀히 여기면서 어떻게 피할 수 있겠습니까?'],
      ['h', '하나님께서도 함께 증언하셨다'],
      ['p', '예수님께서 말씀으로 복음을 선포하셨고, 들은 사람들이 그것을 확증했습니다. 하나님께서도 친히 그 증언에 함께하셨습니다. 표징은 그 너머에 있는 하나님의 능력을 가리켰습니다. 물이 포도주가 되고, 빵 다섯 개와 물고기 두 마리로 수천 명이 먹고, 나사로가 죽은 자 가운데서 살아났습니다. 기이한 일은 사람들을 놀라게 했습니다. 예수님께서 물 위를 걸으시고, 아나니아와 삽비라가 쓰러져 죽고, 빌립보 감옥에 지진이 나서 간수가 두려움에 떨었습니다.'],
      ['p', '기적은 누구에게도 없는 능력을 보여 주었습니다. 나면서부터 눈먼 사람이 보게 되고, 귀신이 쫓겨나고, 거센 풍랑이 잠잠해졌습니다. 그리고 고린도전서 12장에 나오는 것과 같은 성령의 선물들이 하나님의 뜻대로 믿는 사람들에게 주어져, 예수님과 사도들의 말씀을 확증했습니다.']] },
  words: {
    en: {
      attention: { t: 'Pay much closer attention', g: 'perissoterōs prosechein · περισσοτέρως προσέχειν', v: '2:1', s: 'Beyond measure, exceedingly', d: 'Beyond measure, extraordinarily, greatly, exceedingly. The NLT reads: “So we must listen very carefully to the truth we have heard.”' },
      drift: { t: 'Drift away', g: 'pararyōmen · παραρυῶμεν', v: '2:1', s: 'To slip away unnoticed', d: 'To slip away from the listeners, like a boat carried past its mooring by the current. NLT: “or we may drift away from it.”' },
      neglect: { t: 'Neglect', g: 'amelēsantes · ἀμελήσαντες', v: '2:3', s: 'To be careless, show no concern', d: 'Showing no concern; to be careless, to be without care.' },
      witness: { t: 'Also bore witness', g: 'synepimartyrountos · συνεπιμαρτυροῦντος', v: '2:4', s: 'To testify together with', d: 'To attest together with, to join in bearing witness, to unite in adding testimony. God himself did this through signs, wonders, miracles and gifts of the Holy Spirit.' },
      signs: { t: 'Signs', g: 'sēmeia · σημεῖα', v: '2:4', s: 'Events that point beyond themselves', d: 'An event with special meaning, pointing beyond itself to the reality of God’s power. Water into wine, the feeding of the thousands, Lazarus raised.' },
      wonders: { t: 'Wonders', g: 'terata · τέρατα', v: '2:4', s: 'Startling, amazing miracles', d: 'A miracle regarded as startling or amazing. Jesus walking on the water, the earthquake at the Philippian jail.' },
      miracles: { t: 'Miracles', g: 'dynameis · δυνάμεις', v: '2:4', s: 'Works of inherent power', d: 'Something with intrinsic power or inherent ability; the power to carry out a work. Sight for a man born blind, demons cast out, a storm calmed.' },
      gifts: { t: 'Gifts of the Holy Spirit', g: 'merismoi · μερισμοί', v: '2:4', s: 'Distributed by God', d: 'An act of distribution, of sharing out. Given by God to validate and authenticate the words spoken by Jesus and the apostles (1 Cor 12:1–11).' } },
    ko: {
      attention: { t: '더욱 굳게 간직하다', g: 'perissoterōs prosechein · περισσοτέρως προσέχειν', v: '2:1', s: '헤아릴 수 없이, 매우 크게', d: '헤아릴 수 없이, 특별히, 크게, 매우. NLT: “우리가 들은 진리에 매우 주의 깊게 귀 기울여야 합니다.”' },
      drift: { t: '잘못된 길로 빠져들다', g: 'pararyōmen · παραρυῶμεν', v: '2:1', s: '모르는 새 미끄러져 멀어짐', d: '듣는 사람에게서 미끄러져 멀어지는 것. 물살에 떠밀려 정박한 자리를 지나쳐 가는 배와 같습니다.' },
      neglect: { t: '소홀히 하다', g: 'amelēsantes · ἀμελήσαντες', v: '2:3', s: '관심 없음, 부주의함', d: '관심을 두지 않는 것. 부주의하고 돌보지 않는 것.' },
      witness: { t: '함께 증언하다', g: 'synepimartyrountos · συνεπιμαρτυροῦντος', v: '2:4', s: '더불어 증언함', d: '함께 확증하다, 증언에 동참하다, 증언을 더하다. 하나님께서 친히 표징과 기이한 일과 기적과 성령의 선물로 이렇게 하셨습니다.' },
      signs: { t: '표징', g: 'sēmeia · σημεῖα', v: '2:4', s: '그 너머를 가리키는 사건', d: '특별한 의미를 지닌 사건으로, 그 너머에 있는 하나님의 능력의 실체를 가리킵니다. 물이 포도주가 됨, 수천 명을 먹이심, 나사로를 살리심.' },
      wonders: { t: '기이한 일', g: 'terata · τέρατα', v: '2:4', s: '놀랍고 경이로운 일', d: '사람을 놀라게 하고 경탄하게 하는 기적. 물 위를 걸으신 예수님, 빌립보 감옥의 지진.' },
      miracles: { t: '기적', g: 'dynameis · δυνάμεις', v: '2:4', s: '본래의 능력으로 행한 일', d: '본래 지닌 힘이나 능력, 어떤 일을 이루는 권능. 나면서부터 눈먼 사람이 봄, 귀신을 쫓아내심, 풍랑을 잠잠케 하심.' },
      gifts: { t: '성령의 선물', g: 'merismoi · μερισμοί', v: '2:4', s: '하나님께서 나누어 주심', d: '나누어 줌, 분배함. 예수님과 사도들이 전한 말씀을 확증하고 입증하기 위해 하나님께서 주신 것입니다(고전 12:1–11).' } } },
  chips: [
    { id: 'heb1', tag: 'NT', en: 'Heb 1:1–2', ko: '히 1:1–2', ten: 'Long ago, at many times and in many ways, God spoke to our fathers by the prophets, but in these last days he has spoken to us by his Son, whom he appointed the heir of all things, through whom also he created the world.', tko: '하나님께서 옛날에는 예언자들을 통하여, 여러 번에 걸쳐 여러 가지 방법으로 우리 조상들에게 말씀하셨으나, 이 마지막 날에는 아들을 통하여 우리에게 말씀하셨습니다. 하나님께서는 이 아들을 만물의 상속자로 세우셨습니다. 그를 통하여 온 세상을 지으신 것입니다.', wen: '“What we have heard”: the prophets spoke in part, the Son in full.', wko: '“우리가 들은 것”: 예언자들은 부분적으로, 아들은 온전히 말씀하셨습니다.' },
    { id: 'luke1', tag: 'NT', en: 'Luke 1:20', ko: '눅 1:20', ten: 'And behold, you will be silent and unable to speak until the day that these things take place, because you did not believe my words, which will be fulfilled in their time.', tko: '보아라, 그 때가 되면 다 이루어질 내 말을 네가 믿지 않았으므로, 이 일이 이루어지는 날까지, 너는 벙어리가 되어서 말을 못하게 될 것이다.', wen: 'Gabriel to Zechariah: the word of an angel proved reliable.', wko: '가브리엘이 사가랴에게: 천사를 통한 말씀은 그대로 이루어졌습니다.' },
    { id: 'cor12', tag: 'NT', en: '1 Cor 12:11', ko: '고전 12:11', ten: 'All these are empowered by one and the same Spirit, who apportions to each one individually as he wills.', tko: '이 모든 일은 한 분이신 같은 성령이 하시며, 그는 원하시는 대로 각 사람에게 은사를 나누어주십니다.', wen: 'Gifts “distributed according to his will”, as Hebrews 2:4 says.', wko: '히브리서 2:4처럼, “자기의 뜻을 따라” 나누어 주시는 선물입니다.' }] },

{ id: 'm2', num: 'II', range: '5–9', scene: 'crowned', art: '3D · R3F — one light sinks beneath a row of angel lights and dims, then rises above them as a gold ring settles over it.',
  en: { title: 'Crowned with glory and honour', quote: '“But we see him… namely Jesus, crowned with glory and honour.”', sref: 'Hebrews 2:9', cap: 'Scene: one light goes down beneath the angels for a little while, then rises, crowned with a ring of gold.',
    snips: ['Not to angels did God subject the world to come', '“What is man, that you are mindful of him?”', '“You made him for a little while lower than the angels”', 'We do not yet see everything in subjection to him', 'But we see Jesus, crowned with glory and honour'],
    verses: [
      [5, 'For it was not to angels that God subjected the [world|world to come], of which we are speaking.'],
      [6, 'It has been [testified|testified] somewhere, “What is [man|man], that you are [mindful|mindful] of him, or the [son|son of man], that you [care|care] for him?'],
      [7, 'You made him [lower|for a little while lower] than the angels; you have [crowned|crowned] him with [glory|glory] and [honour|honour],'],
      [8, 'putting everything in [subjection|subjection] under his feet.” Now in putting everything in subjection to him, he left nothing outside his control. At present, we do not yet see everything in subjection to him.'],
      [9, 'But we see him who for a little while was made lower than the angels, namely Jesus, crowned with glory and honour because of the [suffering|suffering of death], so that by the grace of God he might [taste|taste death] for everyone.']],
    com: [['h', 'The world to come'],
      ['p', 'In chapter 1 the Son entered the “world”, the inhabited human world, and even the angels worshipped him (1:6). Now the author speaks of the “world to come”: the better, inhabited earth that will come when Jesus returns. It is the kingdom of Jesus Christ, eternal salvation, open to anyone who believes in him. That kingdom will not be looked after by angels, but by Jesus and his brothers and sisters, the believers.'],
      ['h', 'What is man?'],
      ['p', 'The author quotes Psalm 8. There David praises the majesty of God, who made the heavens and the earth, who silences his foes through the cries of children and infants, and who gave people rule over all creation, crowned with glory and honour. Psalm 8 has a double meaning. It speaks of humankind, and ultimately it points to Jesus Christ. “Son of man” here is not yet the title of Jesus; it means human beings.'],
      ['p', 'In verse 8 the “him” and “his” mean humankind. Then comes the word “yet”: we do not yet see everything in subjection. The plan God declared in the psalm is still active; it has not been completed. God did not fail. People failed to reach it, because of sin and because they were enslaved by the fear of death (v15).'],
      ['h', 'But we see Jesus'],
      ['p', 'Verse 9 begins with “but”, in contrast to verses 6–8. Jesus was made lower than the angels for a little while: he took a human body and knew what it feels, suffering, decay, pain, hunger and temptation, all the way to death. He did not fake his death. John records that blood and water came out when his side was pierced (John 19:34), a sign he had already died. He tasted death to the full: not only physical death but spiritual death, the weight of sin and separation from God, when he cried, “My God, my God, why have you forsaken me?” (Matt 27:46).'],
      ['p', 'He had no sin, yet he bore the weight of ours, and through his resurrection he overcame death. So he is crowned with glory and honour, seated at God’s right hand until his enemies, the devil included, become his footstool.'],
      ['q', '“He humbled himself by becoming obedient to the point of death, even death on a cross. Therefore God has highly exalted him and bestowed on him the name that is above every name.” (Phil 2:8–9)']] },
  ko: { title: '영광과 존귀의 면류관', quote: '“예수께서… 영광과 존귀의 면류관을 받아쓰신 것을, 우리가 봅니다.”', sref: '히브리서 2:9', cap: '장면: 한 빛이 잠시 동안 천사들 아래로 내려갔다가, 금빛 고리를 쓰고 다시 떠오릅니다.',
    snips: ['장차 올 세상을 천사들의 지배 아래에 두신 것이 아닙니다', '사람이 무엇이기에 주님께서 그를 기억하여 주시며', '그를 잠시 동안 천사들보다 못하게 하셨으나', '아직도 만물이 다 그에게 복종하고 있는 것은 아닙니다', '영광과 존귀의 면류관을 받아쓰신 예수'],
    verses: [
      [5, '하나님께서는 지금 우리가 말하는 [world|장차 올 세상]을 천사들의 지배 아래에 두신 것이 아닙니다.'],
      [6, '어떤 이가 성경 어딘가에서 이렇게 [testified|증언하였습니다]. “[man|사람]이 무엇이기에 주님께서 그를 [mindful|기억하여] 주시며, [son|인자]가 무엇이기에 주님께서 그를 [care|돌보아] 주십니까?'],
      [7, '주님께서는 그를 [lower|잠시 동안 천사들보다 못하게] 하셨으나, [glory|영광]과 [honour|존귀]의 [crowned|면류관을 그에게 씌워] 주셨으며,'],
      [8, '만물을 그의 발 아래에 [subjection|복종시키셨습니다].” 하나님께서 만물을 사람에게 복종시키심으로써, 그에게 복종하지 않는 것이라고는 아무것도 없게 하신 것입니다. 그러나 지금 우리가 보기로는, 아직도 만물이 다 그에게 복종하고 있는 것은 아닙니다.'],
      [9, '예수께서 다만 잠시 동안 천사들보다 낮아지셔서, [suffering|죽음의 고난]을 당하심으로써, 영광과 존귀의 면류관을 받아쓰신 것을, 우리가 봅니다. 그는 하나님의 은혜로 모든 사람을 위하여 [taste|죽음을 맛보셔야] 했습니다.']],
    com: [['h', '장차 올 세상'],
      ['p', '1장에서 아들은 “세상”, 곧 사람이 사는 세상에 들어오셨고, 천사들까지 그분께 경배했습니다(1:6). 이제 저자는 “장차 올 세상”을 말합니다. 예수님께서 다시 오실 때 올 더 나은, 사람이 사는 땅입니다. 그것은 예수 그리스도의 나라, 곧 영원한 구원이며, 그분을 믿는 사람은 누구나 들어갈 수 있습니다. 그 나라는 천사들이 아니라 예수님과 그분의 형제자매인 믿는 사람들이 돌보게 될 것입니다.'],
      ['h', '사람이 무엇이기에'],
      ['p', '저자는 시편 8편을 인용합니다. 거기서 다윗은 하늘과 땅을 지으시고, 어린이와 젖먹이의 입으로 원수를 잠잠케 하시며, 사람에게 모든 피조물을 다스리게 하시고 영광과 존귀의 관을 씌우신 하나님의 위엄을 찬양합니다. 시편 8편에는 이중의 의미가 있습니다. 인류를 말하면서, 궁극적으로는 예수 그리스도를 가리킵니다. 여기서 “인자”는 아직 예수님의 칭호가 아니라 사람을 뜻합니다.'],
      ['p', '8절의 “그”는 인류를 가리킵니다. 그리고 “아직도”라는 말이 나옵니다. 아직 만물이 다 복종하고 있지 않다는 것입니다. 시편에서 하나님께서 선포하신 계획은 여전히 진행 중이며, 아직 완성되지 않았습니다. 하나님께서 실패하신 것이 아닙니다. 사람들이 죄 때문에, 그리고 죽음의 공포에 매여 종노릇하였기 때문에 거기에 이르지 못한 것입니다(15절).'],
      ['h', '그러나 우리는 예수를 봅니다'],
      ['p', '9절은 6–8절과 대조를 이룹니다. 예수님은 잠시 동안 천사들보다 낮아지셨습니다. 사람의 몸을 입으시고, 그 몸이 느끼는 고난과 쇠함과 아픔과 굶주림과 시험을 겪으시고, 죽음에까지 이르셨습니다. 그분은 죽은 척하신 것이 아닙니다. 요한은 옆구리를 찔렀을 때 피와 물이 나왔다고 기록하는데(요 19:34), 이미 숨을 거두셨다는 표시입니다. 그분은 죽음을 온전히 맛보셨습니다. 육체의 죽음뿐 아니라 영적 죽음, 곧 죄의 무게와 하나님과의 단절을, “나의 하나님, 나의 하나님, 어찌하여 나를 버리셨습니까?” 하고 부르짖으실 때 맛보셨습니다(마 27:46).'],
      ['p', '그분은 죄가 없으셨지만 우리 죄의 무게를 지셨고, 부활로 죽음을 이기셨습니다. 그래서 영광과 존귀의 면류관을 쓰시고, 원수들이, 악마까지도, 그분의 발판이 될 때까지 하나님 우편에 앉아 계십니다.'],
      ['q', '“자기를 낮추시고, 죽기까지 순종하셨으니, 곧 십자가에 죽기까지 하셨습니다. 그러므로 하나님께서는 그를 지극히 높이시고, 모든 이름 위에 뛰어난 이름을 그에게 주셨습니다.” (빌 2:8–9)']] },
  words: {
    en: {
      world: { t: 'World to come', g: 'oikoumenē mellousa · οἰκουμένη μέλλουσα', v: '2:5', s: 'The inhabited earth to come', d: 'The future inhabited earth: the final, perfect and eternal condition of the universe after Jesus Christ returns.' },
      testified: { t: 'Testified', g: 'diemartyrato · διεμαρτύρατο', v: '2:6', s: 'Solemnly affirmed', d: 'To solemnly affirm, to attest: in a serious, sincere and formal manner.' },
      man: { t: 'Man', g: 'anthrōpos · ἄνθρωπος', v: '2:6', s: 'Humankind', d: 'A human, a normal person; mankind, the human race. The race is all humankind as one; human beings are the individual people who make it up.' },
      mindful: { t: 'Mindful', g: 'mimnēskē · μιμνῄσκῃ', v: '2:6', s: 'To remember, keep in mind', d: 'To remember, to recall to mind, to think of again; to keep in mind for attention or consideration.' },
      son: { t: 'Son of man', g: 'huios anthrōpou · υἱὸς ἀνθρώπου', v: '2:6', s: 'Human beings', d: 'Here this does not refer to Jesus but to human beings, parallel to “man” in the line before.' },
      care: { t: 'Care', g: 'episkeptē · ἐπισκέπτῃ', v: '2:6', s: 'To look after', d: 'To look after, to have a care for, to provide for.' },
      lower: { t: 'For a little while lower', g: 'brachy ti ēlattōsas · βραχύ τι ἠλάττωσας', v: '2:7', s: 'Made less, for a short time', d: 'For a short time, for a little; made less or inferior.' },
      crowned: { t: 'Crowned', g: 'estephanōsas · ἐστεφάνωσας', v: '2:7', s: 'The victor’s wreath', d: 'To adorn with an honorary wreath, a ring of flowers, leaves or branches that served as the victor’s “crown” in the Greek public games.' },
      glory: { t: 'Glory', g: 'doxa · δόξα', v: '2:7', s: 'Majestic excellence', d: 'High dignity, honour, majestic excellence that God gave to us and fulfilled in Jesus Christ; outward splendour and the weight of majesty.' },
      honour: { t: 'Honour', g: 'timē · τιμή', v: '2:7', s: 'Recognised worth and authority', d: 'Rightful recognition, high value and royal status; official worth, respect and authority given to a person by a higher power.' },
      subjection: { t: 'Subjection', g: 'hypetaxas · ὑπέταξας', v: '2:8', s: 'Set over all things', d: 'To set one over a thing; to place everything under his rule.' },
      suffering: { t: 'Suffering of death', g: 'pathēma tou thanatou · πάθημα τοῦ θανάτου', v: '2:9', s: 'The whole event of his execution', d: 'The entire, unified event of Jesus’ execution.' },
      taste: { t: 'Taste death', g: 'geusētai thanatou · γεύσηται θανάτου', v: '2:9', s: 'To experience it to the full', d: 'To partake fully, to experience something to the full. Death is the physical separation of the soul from the body.' } },
    ko: {
      world: { t: '장차 올 세상', g: 'oikoumenē mellousa · οἰκουμένη μέλλουσα', v: '2:5', s: '앞으로 올, 사람이 사는 땅', d: '앞으로 올, 사람이 사는 땅. 예수 그리스도께서 다시 오신 뒤 우주의 마지막이자 완전하고 영원한 상태입니다.' },
      testified: { t: '증언하였다', g: 'diemartyrato · διεμαρτύρατο', v: '2:6', s: '엄숙히 확언함', d: '엄숙하게 확언하다, 입증하다. 진지하고 성실하며 격식 있는 태도로.' },
      man: { t: '사람', g: 'anthrōpos · ἄνθρωπος', v: '2:6', s: '인류', d: '사람, 보통의 인간, 인류. 인류는 한 종으로서의 모든 사람이고, 사람은 그 인류를 이루는 한 사람 한 사람입니다.' },
      mindful: { t: '기억하다', g: 'mimnēskē · μιμνῄσκῃ', v: '2:6', s: '마음에 두어 기억함', d: '기억하다, 다시 떠올리다, 다시 생각하다. 관심과 배려의 대상으로 마음에 두다.' },
      son: { t: '인자', g: 'huios anthrōpou · υἱὸς ἀνθρώπου', v: '2:6', s: '사람', d: '여기서는 예수님이 아니라 사람을 가리킵니다. 앞 행의 “사람”과 같은 뜻입니다.' },
      care: { t: '돌보다', g: 'episkeptē · ἐπισκέπτῃ', v: '2:6', s: '보살핌', d: '보살피다, 마음을 쓰다, 필요를 채워 주다.' },
      lower: { t: '잠시 동안 천사들보다 못하게', g: 'brachy ti ēlattōsas · βραχύ τι ἠλάττωσας', v: '2:7', s: '잠시 낮아지게 하심', d: '짧은 동안, 잠시. 더 낮게, 못하게 하다.' },
      crowned: { t: '면류관을 씌우다', g: 'estephanōsas · ἐστεφάνωσας', v: '2:7', s: '승리자의 화관', d: '영예의 화관을 씌우다. 꽃과 잎과 열매와 가지를 둥글게 엮은 것으로, 그리스 경기에서 승리자의 “관”이었습니다.' },
      glory: { t: '영광', g: 'doxa · δόξα', v: '2:7', s: '위엄 있는 탁월함', d: '높은 존엄, 영예, 하나님께서 우리에게 주시고 예수 그리스도 안에서 이루신 위엄 있는 탁월함. 겉으로 드러나는 광채와 위엄의 무게.' },
      honour: { t: '존귀', g: 'timē · τιμή', v: '2:7', s: '인정받는 가치와 권위', d: '마땅한 인정, 높은 가치와 왕의 지위. 더 높은 권위가 한 사람에게 부여한 공적인 가치, 존경, 권위.' },
      subjection: { t: '복종시키다', g: 'hypetaxas · ὑπέταξας', v: '2:8', s: '만물 위에 세우심', d: '어떤 것 위에 세우다. 모든 것을 그의 다스림 아래 두다.' },
      suffering: { t: '죽음의 고난', g: 'pathēma tou thanatou · πάθημα τοῦ θανάτου', v: '2:9', s: '처형의 전 과정', d: '예수님의 처형이라는 하나의 온전한 사건 전체.' },
      taste: { t: '죽음을 맛보다', g: 'geusētai thanatou · γεύσηται θανάτου', v: '2:9', s: '온전히 겪음', d: '온전히 참여하다, 끝까지 경험하다. 죽음은 영혼이 몸에서 분리되는 것입니다.' } } },
  chips: [
    { id: 'ps8', tag: 'OT', en: 'Ps 8:4–6', ko: '시 8:4–6', ten: 'What is man that you are mindful of him, and the son of man that you care for him? Yet you have made him a little lower than the heavenly beings and crowned him with glory and honor. You have given him dominion over the works of your hands; you have put all things under his feet.', tko: '사람이 무엇이기에 주님께서 이렇게까지 생각하여 주시며, 사람의 아들이 무엇이기에 주님께서 이렇게까지 돌보아 주십니까? 주님께서는 그를 하나님보다 조금 못하게 하시고, 그에게 존귀하고 영화로운 왕관을 씌워 주셨습니다. 주님께서 손수 지으신 만물을 다스리게 하시고, 모든 것을 그의 발 아래에 두셨습니다.', wen: 'David’s psalm speaks of humankind, and points ultimately to Jesus.', wko: '다윗의 시편은 인류를 말하면서, 궁극적으로 예수님을 가리킵니다.' },
    { id: 'mt27', tag: 'NT', en: 'Matt 27:46', ko: '마 27:46', ten: 'And about the ninth hour Jesus cried out with a loud voice, saying, “Eli, Eli, lema sabachthani?” that is, “My God, my God, why have you forsaken me?”', tko: '세 시쯤에 예수께서 큰 소리로 부르짖어 말씀하셨다. “엘리 엘리 라마 사박다니?” 그것은 “나의 하나님, 나의 하나님, 어찌하여 나를 버리셨습니까?”라는 뜻이다.', wen: 'He tasted spiritual death too: the weight of sin and separation from God.', wko: '그분은 영적 죽음, 곧 죄의 무게와 하나님과의 단절까지 맛보셨습니다.' },
    { id: 'phil2', tag: 'NT', en: 'Phil 2:8–9', ko: '빌 2:8–9', ten: 'And being found in human form, he humbled himself by becoming obedient to the point of death, even death on a cross. Therefore God has highly exalted him and bestowed on him the name that is above every name.', tko: '자기를 낮추시고, 죽기까지 순종하셨으니, 곧 십자가에 죽기까지 하셨습니다. 그러므로 하나님께서는 그를 지극히 높이시고, 모든 이름 위에 뛰어난 이름을 그에게 주셨습니다.', wen: 'Lowered, then crowned: the same movement as Hebrews 2:9.', wko: '낮아지심, 그리고 면류관: 히브리서 2:9과 같은 흐름입니다.' }] },

{ id: 'm3', num: 'III', range: '10–13', scene: 'gather', art: '3D · R3F — shadow play on a lamplit wall: one robed figure stands in the light; smaller figures walk in from the dark on either side to stand beside him.',
  en: { title: 'Not ashamed to call them brothers', quote: '“Behold, I and the children God has given me.”', sref: 'Hebrews 2:13', cap: 'Scene: one figure stands in the lamplight, and the children come out of the dark to stand beside him.',
    snips: ['The founder of their salvation made perfect through suffering', 'He is not ashamed to call them brothers', '“In the midst of the congregation I will sing your praise”', '“Behold, I and the children God has given me”'],
    verses: [
      [10, 'For it was fitting that he, for whom and by whom all things exist, in bringing many sons to glory, should make the [founder|founder] of their salvation [perfect|perfect] through [suffering|suffering].'],
      [11, 'For he who [sanctifies|sanctifies] and those who are sanctified all have one source. That is why he is not [ashamed|ashamed] to call them [brothers|brothers],'],
      [12, 'saying, “I will tell of your name to my brothers; in the midst of the [congregation|congregation] I will sing your praise.”'],
      [13, 'And again, “I will put my [trust|trust] in him.” And again, “Behold, I and the [children|children] God has given me.”']],
    com: [['h', 'Perfect through suffering'],
      ['p', 'It was fitting for God, for whom and by whom all things exist, to make the founder of our salvation perfect through suffering. “Perfect” does not mean Jesus was once flawed. It means carried through to the full finish: complete, mature, fully developed. The core of perfection comes through suffering. No pain, no gain.'],
      ['p', 'To become the source of salvation for many sons and daughters, Jesus had to suffer and share the weakness of human beings, made a little lower than the angels, who do not feel pain or die. The difference is that he came through it perfect. He had no sin; he overcame temptation and every hardship people face. Some read Psalm 8 as a promise of worldly glory and blessing, but David understood it pointed to the Messiah. Only through Jesus Christ can people receive the promised crown of glory and honour.'],
      ['h', 'One family'],
      ['p', 'He who sanctifies and those who are sanctified have one source. The NLT says it plainly: “So now Jesus and the ones he makes holy have the same Father.” That is why he is not ashamed to call them brothers. The word adelphoi means every believer, man or woman, made one family under God.'],
      ['h', 'A song in the congregation'],
      ['p', 'Psalm 22 was written by David out of deep personal crisis, isolation and persecution by enemies, and it foretells what happened to Jesus in his suffering, crucifixion and its aftermath. Verses 1–21 are cries of distress and agony; verses 22–31 turn to praise for God’s salvation for all nations.'],
      ['p', 'David went into the congregation, told God’s name to his brothers and led them in praise. This foreshadows Jesus. He reveals God’s name: not just a word, but God’s nature, character, goodness, faithfulness and love. And he stands in the midst of the gathered people, leading their worship, and they follow his lead.'],
      ['h', 'I and the children'],
      ['p', 'Isaiah 8 is set around 735–734 BC. The brutal Assyrian empire was threatening to conquer the whole ancient Near East. God’s people were split in two: the Kingdom of Israel in the north and the Kingdom of Judah in the south. Israel and Syria formed an alliance and asked Judah, ruled by King Ahaz, to join. When he refused, they invaded Judah to put a puppet king on the throne. Isaiah warned Ahaz to trust God, but Ahaz panicked and sent a massive bribe of temple gold to the king of Assyria. Assyria agreed to protect him, and Judah became dependent on a pagan empire instead of on God.'],
      ['p', 'Ahaz and the people relied on worldly alliances. Isaiah and his children chose to trust God alone, and they became signs of the faithful remnant who stayed loyal to him. So Jesus became fully human and lived by faith, trusting God as Isaiah did. And as Isaiah stood alongside his children, Jesus stands alongside believers and presents us to God.']] },
  ko: { title: '형제자매라 부르시기를 부끄러워하지 않으심', quote: '“보십시오, 내가 여기에 있습니다. 또 하나님께서 내게 주신 자녀들이 여기에 있습니다.”', sref: '히브리서 2:13', cap: '장면: 한 사람이 등불 빛 속에 서 있고, 자녀들이 어둠 속에서 나와 그 곁에 섭니다.',
    snips: ['그들의 구원의 창시자를 고난으로써 완전하게 하신다', '형제자매라고 부르시기를 부끄러워하지 않으셨습니다', '회중 가운데서 주님을 찬미하겠습니다', '하나님께서 내게 주신 자녀들이 여기에 있습니다'],
    verses: [
      [10, '하나님께서는 만물을 창조하시고, 만물을 보존하시는 분이십니다. 그러므로 하나님께서 많은 자녀를 영광에 이끌어들이실 때에, 그들의 구원의 [founder|창시자]를 [suffering|고난]으로써 [perfect|완전하게] 하신다는 것은 당연한 일입니다.'],
      [11, '[sanctifies|거룩하게 하시는] 분과 거룩하게 되는 사람들은 모두 한 분이신 아버지께 속합니다. 그러하므로 예수께서는 그들을 [brothers|형제자매]라고 부르시기를 [ashamed|부끄러워하지] 않으셨습니다.'],
      [12, '그리하여 그분은 “내가 주님의 이름을 내 형제자매들에게 선포하며, [congregation|회중] 가운데서 주님을 찬미하겠습니다” 하고 말씀하시고,'],
      [13, '또 “나는 그를 [trust|신뢰하겠습니다]” 하고 말씀하시고, “보십시오, 내가 여기에 있습니다. 또 하나님께서 내게 주신 [children|자녀들]이 여기에 있습니다” 하고 말씀하셨습니다.']],
    com: [['h', '고난으로써 완전하게'],
      ['p', '만물을 창조하시고 보존하시는 하나님께서 우리 구원의 창시자를 고난으로써 완전하게 하시는 것은 당연한 일입니다. “완전하게 하다”는 예수님께 한때 흠이 있었다는 뜻이 아닙니다. 끝까지 온전히 이루어 낸다는 뜻입니다. 완성되고, 성숙하고, 온전히 자란 상태입니다. 완전함의 핵심은 고난을 통해 옵니다. 고통 없이는 얻는 것도 없습니다.'],
      ['p', '많은 자녀의 구원의 근원이 되시려고, 예수님은 고난을 받으시고 사람의 연약함을 함께 겪으셔야 했습니다. 아픔도 죽음도 겪지 않는 천사들보다 잠시 낮아지신 것입니다. 다른 점은 그분이 그 모든 것을 완전하게 통과하셨다는 것입니다. 그분은 죄가 없으셨고, 시험과 사람이 겪는 모든 어려움을 이기셨습니다. 어떤 이들은 시편 8편을 세상의 영광과 복에 대한 약속으로 읽었지만, 다윗은 그것이 메시아를 가리킨다는 것을 알았습니다. 오직 예수 그리스도를 통해서만 사람은 약속된 영광과 존귀의 면류관을 받을 수 있습니다.'],
      ['h', '한 가족'],
      ['p', '거룩하게 하시는 분과 거룩하게 되는 사람들은 한 근원에서 났습니다. NLT는 이렇게 분명히 말합니다. “이제 예수님과 그분이 거룩하게 하시는 사람들은 같은 아버지를 모십니다.” 그래서 그분은 그들을 형제자매라 부르기를 부끄러워하지 않으십니다. 아델포이라는 단어는 남녀를 가리지 않고 하나님 아래 한 가족이 된 모든 믿는 사람을 뜻합니다.'],
      ['h', '회중 가운데서 부르는 찬송'],
      ['p', '시편 22편은 다윗이 깊은 개인적 위기와 고립과 원수들의 핍박 가운데 쓴 시로, 예수님의 고난과 십자가와 그 이후에 실제로 일어난 일을 미리 보여 줍니다. 1–21절은 고통과 괴로움의 부르짖음이고, 22–31절은 모든 민족을 향한 하나님의 구원을 찬양합니다.'],
      ['p', '다윗은 회중 가운데로 나아가 형제들에게 하나님의 이름을 전하고 그들을 이끌어 찬양했습니다. 이는 예수님을 미리 보여 줍니다. 그분은 하나님의 이름을 드러내십니다. 단순한 이름이 아니라 하나님의 본성과 성품, 선하심과 신실하심과 사랑입니다. 그리고 모인 백성 한가운데 서셔서 예배를 이끄시고, 그들은 그분을 따릅니다.'],
      ['h', '나와 자녀들'],
      ['p', '이사야 8장의 배경은 주전 735–734년경입니다. 잔혹하고 거대한 앗시리아 제국이 고대 근동 전체를 정복하려 위협하고 있었습니다. 하나님의 백성은 북쪽의 이스라엘 왕국과 남쪽의 유다 왕국으로 나뉘어 있었습니다. 이스라엘과 시리아는 동맹을 맺고 아하스 왕이 다스리던 유다에게 합류를 요구했습니다. 아하스가 거절하자 그들은 꼭두각시 왕을 세우려고 유다를 침략했습니다. 이사야는 하나님을 신뢰하라고 경고했지만, 아하스는 두려움에 빠져 성전의 금을 앗시리아 왕에게 막대한 뇌물로 보냈습니다. 앗시리아는 보호를 약속했고, 유다는 하나님 대신 이방 제국에 기대게 되었습니다.'],
      ['p', '아하스와 백성은 세상의 동맹을 의지했습니다. 이사야와 그의 자녀들은 오직 하나님만 신뢰하기로 했고, 하나님께 끝까지 충성한 남은 자들의 징조가 되었습니다. 이처럼 예수님도 온전한 사람이 되셔서 이사야처럼 믿음으로 살며 하나님을 신뢰하셨습니다. 그리고 이사야가 자녀들과 함께 섰듯이, 예수님은 믿는 사람들 곁에 서셔서 우리를 하나님께 드리십니다.']] },
  words: {
    en: {
      founder: { t: 'Founder', g: 'archēgos · ἀρχηγός', v: '2:10', s: 'The one who leads the way', d: 'The founder of the salvation of the many sons and daughters is Jesus Christ, the one who goes first and leads them into glory.' },
      perfect: { t: 'Perfect', g: 'teleiōsai · τελειῶσαι', v: '2:10', s: 'Carried through to the full finish', d: 'To accomplish, to bring to an end; to be complete, mature, fully developed, full grown. It does not mean to terminate something, but to carry it out to the full finish.' },
      suffering: { t: 'Suffering', g: 'pathēmata · παθήματα', v: '2:10', s: 'Affliction from outside', d: 'External suffering: misfortune, calamity, evil, affliction.' },
      sanctifies: { t: 'Sanctified', g: 'hagiazōn · ἁγιάζων', v: '2:11', s: 'Set apart, made holy', d: 'Set apart for sacred purposes; to make holy. NLT: “So now Jesus and the ones he makes holy have the same Father.”' },
      ashamed: { t: 'Ashamed', g: 'epaischynetai · ἐπαισχύνεται', v: '2:11', s: 'The blush of exposure', d: 'A consciousness of guilt or of its exposure, causing one to blush; the fear of embarrassment.' },
      brothers: { t: 'Brothers', g: 'adelphoi · ἀδελφοί', v: '2:11', s: 'One family under God', d: 'Any believers of God, male or female, who become one family under God.' },
      congregation: { t: 'Congregation', g: 'ekklēsia · ἐκκλησία', v: '2:12', s: 'An assembly called together', d: 'An assembly or gathering of people called together for a specific purpose.' },
      trust: { t: 'Trust', g: 'pepoithōs · πεποιθώς', v: '2:13', s: 'Confidence in God', d: 'To have confidence; to be confident.' },
      children: { t: 'Children', g: 'paidia · παιδία', v: '2:13', s: 'Followers of Jesus', d: 'A child or children recently born. Here it is used figuratively for the followers of Jesus Christ.' } },
    ko: {
      founder: { t: '창시자', g: 'archēgos · ἀρχηγός', v: '2:10', s: '앞서 이끄시는 분', d: '많은 자녀의 구원의 창시자는 예수 그리스도이십니다. 먼저 가셔서 그들을 영광으로 이끄시는 분입니다.' },
      perfect: { t: '완전하게 하다', g: 'teleiōsai · τελειῶσαι', v: '2:10', s: '끝까지 온전히 이룸', d: '이루다, 끝에 이르게 하다. 완성되고 성숙하고 온전히 자란 상태. 무언가를 끝내 버린다는 뜻이 아니라 끝까지 온전히 이루어 낸다는 뜻입니다.' },
      suffering: { t: '고난', g: 'pathēmata · παθήματα', v: '2:10', s: '밖에서 오는 괴로움', d: '외부에서 오는 고난. 불행, 재난, 악, 괴로움.' },
      sanctifies: { t: '거룩하게 하다', g: 'hagiazōn · ἁγιάζων', v: '2:11', s: '구별하여 거룩하게 함', d: '거룩한 목적을 위해 구별하다, 거룩하게 하다. NLT: “이제 예수님과 그분이 거룩하게 하시는 사람들은 같은 아버지를 모십니다.”' },
      ashamed: { t: '부끄러워하다', g: 'epaischynetai · ἐπαισχύνεται', v: '2:11', s: '드러남에 얼굴 붉힘', d: '허물이나 그것이 드러남을 의식하여 얼굴을 붉히는 것. 창피를 당할까 하는 두려움.' },
      brothers: { t: '형제자매', g: 'adelphoi · ἀδελφοί', v: '2:11', s: '하나님 아래 한 가족', d: '남녀를 가리지 않고 하나님을 믿는 모든 사람. 하나님 아래 한 가족이 됩니다.' },
      congregation: { t: '회중', g: 'ekklēsia · ἐκκλησία', v: '2:12', s: '부름받아 모인 무리', d: '특정한 목적을 위해 함께 부름받아 모인 사람들의 모임.' },
      trust: { t: '신뢰하다', g: 'pepoithōs · πεποιθώς', v: '2:13', s: '하나님을 향한 확신', d: '확신을 가지다, 믿고 의지하다.' },
      children: { t: '자녀들', g: 'paidia · παιδία', v: '2:13', s: '예수님을 따르는 사람들', d: '갓 태어난 아이 또는 아이들. 여기서는 예수 그리스도를 따르는 사람들을 비유적으로 가리킵니다.' } } },
  chips: [
    { id: 'ps22', tag: 'OT', en: 'Ps 22:22', ko: '시 22:22', ten: 'I will tell of your name to my brothers; in the midst of the congregation I will praise you.', tko: '주님의 이름을 나의 백성에게 전하고, 예배 드리는 회중 한가운데서, 주님을 찬양하렵니다.', wen: 'David’s psalm of agony turns to praise at verse 22. Jesus leads that song among his people.', wko: '다윗의 고통의 시편은 22절에서 찬양으로 바뀝니다. 예수님은 그 노래를 자기 백성 가운데서 이끄십니다.' },
    { id: 'isa817', tag: 'OT', en: 'Isa 8:17', ko: '사 8:17', ten: 'I will wait for the LORD, who is hiding his face from the house of Jacob, and I will hope in him.', tko: '주님께서 비록 야곱의 집에서 얼굴을 돌리셔도, 나는 주님을 기다리겠다. 나는 주님을 의지하겠다.', wen: 'While King Ahaz trusted Assyria, Isaiah trusted God alone.', wko: '아하스 왕이 앗시리아를 의지할 때, 이사야는 오직 하나님만 신뢰했습니다.' },
    { id: 'isa818', tag: 'OT', en: 'Isa 8:18', ko: '사 8:18', ten: 'Behold, I and the children whom the LORD has given me are signs and portents in Israel from the LORD of hosts, who dwells on Mount Zion.', tko: '내가 여기에 있고, 주님께서 나에게 주신 이 아이들이 여기에 있다. 나와 아이들은, 시온 산에 계시는 만군의 주님께서 이스라엘에게 보여 주시는, 살아 있는 징조와 예표다.', wen: 'Isaiah and his children, a faithful remnant. Jesus stands the same way with those God has given him.', wko: '이사야와 그의 자녀들, 신실한 남은 자. 예수님도 하나님께서 주신 사람들과 그렇게 함께 서십니다.' }] },

{ id: 'm4', num: 'IV', range: '14–18', scene: 'freed', art: '3D · R3F — a chain of dim links holds a row of lights down; one light descends into it, the links break and scatter, and the captives rise.',
  en: { title: 'Made like his brothers', quote: '“…that through death he might destroy the one who has the power of death.”', sref: 'Hebrews 2:14', cap: 'Scene: a light enters the chain that holds the others. The links break, and the captives rise.',
    snips: ['He himself likewise partook of flesh and blood', 'Deliver all those who through fear of death were subject to slavery', 'He helps the offspring of Abraham', 'A merciful and faithful high priest', 'He is able to help those who are being tempted'],
    verses: [
      [14, 'Since therefore the children share in [flesh|flesh and blood], he himself likewise [partook|partook of the same things], that through [death|death] he might destroy the one who has the [power|power of death], that is, the [devil|devil],'],
      [15, 'and deliver all those who through [fear|fear of death] were subject to lifelong slavery.'],
      [16, 'For surely it is not angels that he helps, but he helps the [offspring|offspring of Abraham].'],
      [17, 'Therefore he had to be made like his brothers in every respect, so that he might become a [merciful|merciful] and [faithful|faithful] [priest|high priest] in the service of God, to make [propitiation|propitiation] for the sins of the people.'],
      [18, 'For because he himself has suffered when tempted, he is able to help those who are being tempted.']],
    com: [['h', 'Flesh and blood'],
      ['p', 'The NLT puts verse 14 simply: “Because God’s children are human beings, made of flesh and blood, the Son also became flesh and blood.” The children are human, so Jesus Christ took on the same nature, one that did not naturally belong to him.'],
      ['h', 'The power of death'],
      ['p', 'The devil holding the power of death does not mean he decides between life and death. That authority is God’s. It means a legal and psychological dominion that comes through sin. “Devil” means slanderer or accuser. He tempts people into sin and leads them toward eternal spiritual death and separation from God. Then he accuses them, telling them they can never be restored.'],
      ['p', 'So people are held in fear: hopeless, rebellious, easily manipulated, spiritually enslaved, pulled again and again toward sin. Jesus broke that chain. He went through the whole cycle of physical and spiritual death, and through the resurrection he broke death’s dominion. He showed us the way of hope: to be a spiritual family with Jesus Christ, not slaves to sin.'],
      ['h', 'Offspring of Abraham'],
      ['p', 'He helps not angels but the offspring of Abraham. In Genesis 12, 18 and 22 God says three times that Abraham will become a great nation and that his offspring will be blessed. Paul explains in Galatians 3:7–9 that those who have faith are the children of Abraham. Scripture foresaw that God would justify the Gentiles by faith, so all who rely on faith are blessed along with Abraham, the man of faith.'],
      ['h', 'A merciful and faithful high priest'],
      ['p', 'The high priest was chief over all the other priests in Israel, an office God first established through Moses. He was the mediator between God and Israel. He offered sacrifices and rituals like the other priests, and once a year he entered the Most Holy Place to represent the sins of the nation.'],
      ['p', 'Jesus had to be made like his brothers in every respect to become that high priest: merciful, concerned for people in their need, and faithful, keeping every promise. He made propitiation, taking the judgement for human sin, satisfying God’s justice and offering mercy. And because he himself suffered when tempted, he understands us, and he is able to help us.']] },
  ko: { title: '모든 점에서 형제자매와 같아지심', quote: '“…그가 죽음을 겪으시고서, 죽음의 세력을 쥐고 있는 자 곧 악마를 멸하시고”', sref: '히브리서 2:14', cap: '장면: 한 빛이 다른 빛들을 묶고 있는 사슬 속으로 들어갑니다. 고리가 끊어지고, 갇혔던 빛들이 떠오릅니다.',
    snips: ['그도 역시 피와 살을 가지셨습니다', '죽음의 공포 때문에 종노릇하는 사람들을 해방시키시기 위함이었습니다', '아브라함의 자손들을 도와주십니다', '자비롭고 성실한 대제사장', '시험을 받는 사람들을 도우실 수 있습니다'],
    verses: [
      [14, '이 자녀들은 [flesh|피와 살]을 가진 사람들이기에, 그도 역시 [partook|피와 살을 가지셨습니다]. 그것은, 그가 [death|죽음]을 겪으시고서, [power|죽음의 세력]을 쥐고 있는 자 곧 [devil|악마]를 멸하시고,'],
      [15, '또 일생 동안 [fear|죽음의 공포] 때문에 종노릇하는 사람들을 해방시키시기 위함이었습니다.'],
      [16, '사실, 주님께서는 천사들을 도와주시는 것이 아니라, [offspring|아브라함의 자손들]을 도와주십니다.'],
      [17, '그러므로 그는 모든 점에서 형제자매들과 같아지셔야만 했습니다. 그것은, 그가 하나님 앞에서 [merciful|자비롭고] [faithful|성실한] [priest|대제사장]이 되심으로써, 백성의 [propitiation|죄를 대신 갚으시기] 위한 것입니다.'],
      [18, '그는 몸소 시험을 받아서 고난을 당하셨으므로, 시험을 받는 사람들을 도우실 수 있습니다.']],
    com: [['h', '피와 살'],
      ['p', 'NLT는 14절을 이렇게 쉽게 옮깁니다. “하나님의 자녀들은 피와 살로 된 사람이기에, 아들도 피와 살이 되셨습니다.” 자녀들이 사람이기에, 예수 그리스도께서는 본래 그분께 속하지 않은 같은 본성을 입으셨습니다.'],
      ['h', '죽음의 세력'],
      ['p', '악마가 죽음의 세력을 쥐고 있다는 것은 그가 삶과 죽음을 결정한다는 뜻이 아닙니다. 그 권한은 하나님께 있습니다. 죄로 말미암은 법적이고 심리적인 지배를 뜻합니다. “악마”는 비방하는 자, 고발하는 자라는 뜻입니다. 그는 사람을 죄로 유혹하여 영원한 영적 죽음과 하나님과의 단절로 이끕니다. 그리고 결코 회복될 수 없다고 고발합니다.'],
      ['p', '그래서 사람들은 두려움에 붙잡힙니다. 소망을 잃고, 거역하고, 쉽게 휘둘리고, 영적으로 매여, 거듭 죄로 끌려갑니다. 예수님께서 그 사슬을 끊으셨습니다. 육체와 영의 죽음 전체를 겪으시고, 부활로 죽음의 지배를 깨뜨리셨습니다. 그리고 우리에게 소망의 길을 보여 주셨습니다. 죄의 종이 아니라 예수 그리스도와 한 영적 가족이 되는 길입니다.'],
      ['h', '아브라함의 자손'],
      ['p', '그분은 천사들이 아니라 아브라함의 자손을 도우십니다. 창세기 12장, 18장, 22장에서 하나님은 세 번이나 아브라함이 큰 민족이 되고 그 자손이 복을 받을 것이라고 말씀하십니다. 바울은 갈라디아서 3:7–9에서 믿음에서 난 사람들이 아브라함의 자손이라고 설명합니다. 성경은 하나님께서 이방 사람을 믿음으로 의롭다 하실 것을 미리 알았고, 그래서 믿음을 의지하는 모든 사람은 믿음의 사람 아브라함과 함께 복을 받습니다.'],
      ['h', '자비롭고 성실한 대제사장'],
      ['p', '대제사장은 이스라엘의 모든 제사장 위에 있는 우두머리로, 하나님께서 모세를 통해 처음 세우신 직분입니다. 그는 하나님과 이스라엘 사이의 중재자였습니다. 다른 제사장들처럼 제사와 의식을 드렸고, 해마다 한 번 지성소에 들어가 온 민족의 죄를 대신하여 섰습니다.'],
      ['p', '예수님은 그런 대제사장이 되시려고 모든 점에서 형제자매들과 같아지셔야 했습니다. 자비로우셔서 어려움에 처한 사람들을 마음에 두시고, 성실하셔서 모든 약속을 지키십니다. 그분은 인간의 죄에 대한 심판을 대신 받으셔서 하나님의 공의를 만족시키시고 자비를 베푸셨습니다. 그리고 몸소 시험을 받아 고난을 당하셨기에, 우리를 이해하시고 도우실 수 있습니다.']] },
  words: {
    en: {
      flesh: { t: 'Flesh and blood', g: 'haimatos kai sarkos · αἵματος καὶ σαρκός', v: '2:14', s: 'Physical human beings', d: 'Flesh is the covering of a living creature: physical human beings, the physical flesh of people. Blood is the actual blood in people.' },
      partook: { t: 'Partook of the same things', g: 'meteschen · μετέσχεν', v: '2:14', s: 'Took hold of a nature not his own', d: 'Literally to hold with, and so to share in the possession of something; taking hold of something that is not naturally one’s own kind.' },
      death: { t: 'Death', g: 'thanatos · θάνατος', v: '2:14', s: 'The end of life on earth', d: 'The death of the body: the separation of the soul from the body, by which life on earth is ended.' },
      power: { t: 'Power of death', g: 'kratos · κράτος', v: '2:14', s: 'Dominion, the power to rule', d: 'Dominion, the power to rule or control. The devil’s hold is legal and psychological, through sin; the authority over life and death is God’s.' },
      devil: { t: 'Devil', g: 'diabolos · διάβολος', v: '2:14', s: 'Slanderer, accuser', d: 'Slanderer or accuser. He tempts people into sin, then accuses them, telling them they cannot be restored.' },
      fear: { t: 'Fear of death', g: 'phobos · φόβος', v: '2:15', s: 'Alarm, terror', d: 'Alarm, terror or fright.' },
      offspring: { t: 'Offspring of Abraham', g: 'sperma Abraam · σπέρμα Ἀβραάμ', v: '2:16', s: 'The family of faith', d: 'Seed, descendants; children, family, race, posterity. Those who have faith are the children of Abraham (Gal 3:7).' },
      merciful: { t: 'Merciful', g: 'eleēmōn · ἐλεήμων', v: '2:17', s: 'Compassion in thought and action', d: 'Compassionate; one who is kindly merciful in thought and in action, concerned about people in their need.' },
      faithful: { t: 'Faithful', g: 'pistos · πιστός', v: '2:17', s: 'Trustworthy, keeps promises', d: 'Trustworthy, dependable, reliable; one who keeps promises.' },
      priest: { t: 'High priest', g: 'archiereus · ἀρχιερεύς', v: '2:17', s: 'Mediator between God and people', d: 'The chief over all the other priests in Israel, established by God through Moses. He mediated between God and Israel, offered sacrifices, and once a year represented the sins of the nation in the Most Holy Place.' },
      propitiation: { t: 'Propitiation', g: 'hilaskesthai · ἱλάσκεσθαι', v: '2:17', s: 'Judgement taken, mercy offered', d: 'The act of regaining favour, making things right, turning away someone’s anger. Jesus Christ took the judgement for human sin, satisfying God’s justice and offering mercy.' } },
    ko: {
      flesh: { t: '피와 살', g: 'haimatos kai sarkos · αἵματος καὶ σαρκός', v: '2:14', s: '육체를 지닌 사람', d: '살은 살아 있는 존재를 덮고 있는 것, 곧 육체를 지닌 사람, 사람의 몸입니다. 피는 사람 안에 흐르는 실제 피입니다.' },
      partook: { t: '피와 살을 가지셨다', g: 'meteschen · μετέσχεν', v: '2:14', s: '본래 자기 것이 아닌 본성을 입으심', d: '문자적으로 함께 붙들다, 그래서 어떤 것을 함께 소유하다. 본래 자기와 같은 종류가 아닌 것을 취하는 것.' },
      death: { t: '죽음', g: 'thanatos · θάνατος', v: '2:14', s: '이 땅의 삶이 끝남', d: '몸의 죽음. 영혼이 몸에서 분리되어 이 땅의 삶이 끝나는 것.' },
      power: { t: '죽음의 세력', g: 'kratos · κράτος', v: '2:14', s: '지배, 다스리는 힘', d: '지배, 다스리거나 통제하는 힘. 악마의 힘은 죄를 통한 법적, 심리적 지배이며, 삶과 죽음의 권한은 하나님께 있습니다.' },
      devil: { t: '악마', g: 'diabolos · διάβολος', v: '2:14', s: '비방하는 자, 고발하는 자', d: '비방하는 자, 고발하는 자. 사람을 죄로 유혹한 뒤, 결코 회복될 수 없다고 고발합니다.' },
      fear: { t: '죽음의 공포', g: 'phobos · φόβος', v: '2:15', s: '놀람, 두려움', d: '놀람, 공포, 두려움.' },
      offspring: { t: '아브라함의 자손들', g: 'sperma Abraam · σπέρμα Ἀβραάμ', v: '2:16', s: '믿음의 가족', d: '씨, 후손. 자녀, 가족, 민족, 자손. 믿음에서 난 사람들이 아브라함의 자손입니다(갈 3:7).' },
      merciful: { t: '자비로운', g: 'eleēmōn · ἐλεήμων', v: '2:17', s: '생각과 행동의 긍휼', d: '긍휼히 여기는, 생각과 행동으로 자비를 베푸는, 어려움에 처한 사람들을 마음에 두는.' },
      faithful: { t: '성실한', g: 'pistos · πιστός', v: '2:17', s: '믿을 수 있고 약속을 지킴', d: '믿을 만하고, 의지할 수 있고, 신뢰할 수 있는. 약속을 지키는.' },
      priest: { t: '대제사장', g: 'archiereus · ἀρχιερεύς', v: '2:17', s: '하나님과 백성 사이의 중재자', d: '이스라엘의 모든 제사장 위에 있는 우두머리로, 하나님께서 모세를 통해 세우셨습니다. 하나님과 이스라엘 사이를 중재하고 제사를 드렸으며, 해마다 한 번 지성소에서 민족의 죄를 대신하여 섰습니다.' },
      propitiation: { t: '죄를 대신 갚다', g: 'hilaskesthai · ἱλάσκεσθαι', v: '2:17', s: '심판을 받으시고 자비를 베푸심', d: '호의를 다시 얻는 것, 바로잡는 것, 누군가의 진노를 가라앉히는 것. 예수 그리스도께서 인간의 죄에 대한 심판을 받으셔서 하나님의 공의를 만족시키시고 자비를 베푸셨습니다.' } } },
  chips: [
    { id: 'gal3', tag: 'NT', en: 'Gal 3:7–9', ko: '갈 3:7–9', ten: 'Know then that it is those of faith who are the sons of Abraham. And the Scripture, foreseeing that God would justify the Gentiles by faith, preached the gospel beforehand to Abraham, saying, “In you shall all the nations be blessed.” So then, those who are of faith are blessed along with Abraham, the man of faith.', tko: '그러므로 믿음에서 난 사람들이야말로 아브라함의 자손임을 여러분은 아십시오. 또 하나님께서 이방 사람을 믿음에 근거하여 의롭다고 여겨 주신다는 것을 성경은 미리 알고서, 아브라함에게 “모든 민족이 너로 말미암아 복을 받을 것이다” 하는 기쁜 소식을 미리 전하였습니다. 그러므로 믿음에서 난 사람들은 믿음을 가진 아브라함과 함께 복을 받습니다.', wen: 'Who the “offspring of Abraham” are: everyone who has faith.', wko: '“아브라함의 자손”은 누구인가: 믿음을 가진 모든 사람입니다.' }] }
];

const SUM: Record<Lang, Summary> = {
  en: { groups: [
      { h: 'A warning to hold fast', items: [['vv1–4', 'Pay much closer attention to Jesus Christ. The message from angels was real, but the word of Jesus carries far more power, and God testified to it by signs, wonders, miracles and gifts.']] },
      { h: 'Why the Son became one of us', items: [['vv5–9', 'Made a little lower than the angels like all humankind, Jesus became the one crowned with glory and honour because of what he fully experienced.'], ['vv10–13', 'Jesus is not ashamed to call believers his family, children of the same Father.'], ['vv14–18', 'He took on flesh and blood to break the power of death and the devil and free those held in slavery. He is now the merciful and faithful high priest who makes atonement for the sins of the people.']] }],
    intentH: 'The author’s intention', intentShort: 'To show why Jesus had to suffer. To become the perfect source of salvation, he shared everything humans feel, even death, and broke its power by rising again.',
    intent: ['For Jesus to become the perfect source of salvation, he too had to suffer and experience what humans feel.', 'In the end Jesus fully experienced the physical death that all humans experience. But instead of dying permanently, he broke the cycle of physical and spiritual death by his resurrection, and opened the way of hope for all who believe in him.', 'Jesus is now our high priest before God. He understands us, and he is able to help us, because of what he went through.'] },
  ko: { groups: [
      { h: '굳게 붙들라는 경고', items: [['1–4절', '예수 그리스도께 더욱 주의를 기울이십시오. 천사들을 통한 말씀도 참되었지만, 예수님의 말씀은 훨씬 더 큰 능력이 있으며, 하나님께서 표징과 기이한 일과 기적과 선물로 그것을 증언하셨습니다.']] },
      { h: '아들이 우리 중 하나가 되신 이유', items: [['5–9절', '모든 사람처럼 천사들보다 잠시 낮아지신 예수님은, 온전히 겪으신 일 때문에 영광과 존귀의 면류관을 쓰신 분이 되셨습니다.'], ['10–13절', '예수님은 믿는 사람들을 같은 아버지를 모신 가족이라 부르기를 부끄러워하지 않으십니다.'], ['14–18절', '피와 살을 입으셔서 죽음과 악마의 세력을 깨뜨리시고 종노릇하던 사람들을 해방시키셨습니다. 이제 그분은 백성의 죄를 대신 갚으시는 자비롭고 성실한 대제사장이십니다.']] }],
    intentH: '저자의 의도', intentShort: '예수님께서 왜 고난을 받으셔야 했는지 보여 주는 것. 완전한 구원의 근원이 되시려고 그분은 죽음까지 사람이 느끼는 모든 것을 겪으시고, 다시 살아나심으로 그 세력을 깨뜨리셨습니다.',
    intent: ['예수님께서 완전한 구원의 근원이 되시려면, 그분도 고난을 받고 사람이 느끼는 것을 겪으셔야 했습니다.', '마침내 예수님은 모든 사람이 겪는 육체의 죽음을 온전히 겪으셨습니다. 그러나 영원히 죽으신 것이 아니라, 부활로 육체와 영의 죽음의 굴레를 끊으시고, 그분을 믿는 모든 사람에게 소망의 길을 여셨습니다.', '예수님은 이제 하나님 앞에서 우리의 대제사장이십니다. 그분이 겪으신 일 때문에 우리를 이해하시고, 도우실 수 있습니다.'] }
};

const COPY: Record<Lang, ChapterCopy> = {
  en: { heroEyebrow: 'A verse-by-verse study · ESV', heroTitle: 'Hebrews 2',
    tagline: '“How shall we escape if we neglect such a great salvation?”', taglineRef: 'Hebrews 2:3',
    mapTitle: 'Eighteen verses, four movements', mapIntro: 'Hold fast to what you have heard. The Son is made lower than the angels, tastes death for everyone, calls us his family, and breaks the power of death as our high priest.',
    summaryTitle: 'What Hebrews 2 says', footQuote: '“He is able to help those who are being tempted.”', version: 'ESV' },
  ko: { heroEyebrow: '한 절씩 읽는 성경 공부 · 새번역', heroTitle: '히브리서 2장',
    tagline: '“하물며 우리가 이렇게도 귀중한 구원을 소홀히 하고서야, 어떻게 그 갚음을 피할 수 있겠습니까?”', taglineRef: '히브리서 2:3',
    mapTitle: '열여덟 절, 네 흐름', mapIntro: '들은 바를 굳게 간직하십시오. 아들은 천사들보다 낮아지시고, 모든 사람을 위해 죽음을 맛보시며, 우리를 가족이라 부르시고, 대제사장으로서 죽음의 세력을 깨뜨리십니다.',
    summaryTitle: '히브리서 2장이 말하는 것', footQuote: '“시험을 받는 사람들을 도우실 수 있습니다”', version: '새번역' }
};

export const chapter2: ChapterContent = { number: 2, setting: 'earth', copy: COPY, movements: MV, summary: SUM };
