import type { ChapterContent, ChapterCopy, Lang, Movement, Summary } from "../types";

// Verse strings mark key words as [key|display text]; see content/parse.ts.
const MV: Movement[] = [
{ id: 'm1', num: 'I', range: '1–6', scene: 'tabernacle', art: '3D · R3F — the tabernacle in the wilderness at dusk: posts and white linen raise the courtyard, the altar is lit, the tent is pitched, and the cloud of glory settles on it.',
  en: { title: 'Consider Jesus', quote: '“Christ is faithful over God’s house as a son. And we are his house.”', sref: 'Hebrews 3:6', cap: 'Scene: the tabernacle, God’s house in Moses’ day, is set up in the wilderness, and the glory of the LORD settles on it.',
    snips: ['Consider Jesus, the apostle and high priest of our confession', 'Faithful, just as Moses was faithful in all God’s house', 'The builder has more honour than the house', 'The builder of all things is God', 'Moses, a servant, testified to what would be spoken later', 'Christ is faithful over God’s house as a son. We are his house'],
    verses: [
      [1, 'Therefore, [holy|holy] brothers, you who share in a [calling|heavenly calling], [consider|consider] Jesus, the [apostle|apostle] and [priest|high priest] of our [confession|confession],'],
      [2, 'who was [faithful|faithful] to him who appointed him, just as Moses also was faithful in all [house|God’s house].'],
      [3, 'For Jesus has been counted worthy of more [glory|glory] than Moses—as much more glory as the [builder|builder of a house] has more honour than the house itself.'],
      [4, '(For every house is built by someone, but the builder of all things is God.)'],
      [5, 'Now Moses was faithful in all God’s house as a [servant|servant], to testify to the things that were to be spoken later,'],
      [6, 'but Christ is faithful over God’s house as a [son|son]. And we are his house, if indeed we hold fast our [confidence|confidence] and our [boasting|boasting] in our hope.']],
    com: [['h', 'Therefore, consider Jesus'],
      ['p', 'Chapter 3 begins with “therefore”: it follows from chapter 2. There Jesus shared in flesh and blood, tasted death, broke its power, and became a merciful and faithful high priest who can help those who are tempted, because he was tempted and overcame. So the author says: consider him. The NLT reads “think carefully about this Jesus”; the NIV, “fix your thoughts on Jesus.”'],
      ['p', 'The readers are called holy, set apart for God, and they already share in a heavenly calling, God’s invitation to eternal salvation in the “world to come” (2:5). That is exactly why they must put their minds on Jesus. They have heard the gospel and have the pathway to heaven, yet it is possible to have all that and still stop considering him. Jesus is the apostle, the one God sent with his full authority, and the high priest, the one who stands between God and his people. Our confession is what we openly declare together: that Jesus is Lord.'],
      ['h', 'Moses, faithful in the house'],
      ['p', 'Moses was one of the most important figures in Israel’s history. God raised him as a prophet and spoke with him face to face, clearly and not in riddles, visions or dreams (Num 12:6–8). He received the law on stone tablets at Sinai and wrote the first five books of the Old Testament, the Pentateuch (모세오경). And he was faithful in all God’s house.'],
      ['p', 'In Moses’ day “God’s house” was the tabernacle where the community worshipped. But the house is more than a building. It is also the people who gather to worship: a physical place and a spiritual community. Every house has a builder, and the builder of all things is God. He is behind the tabernacle, and behind the people who worship in it. Jesus, through whom God created the world (1:2), is that builder too, and the builder has more honour than the house.'],
      ['h', 'A servant and a son'],
      ['p', 'Moses served as a therapōn, not a common slave but a servant who serves willingly and truly cares for his master’s interests. His role was not only to serve but to testify to “the things that were to be spoken later”: what God would say in these last days through his Son (1:2). The law was a foreshadowing of Jesus. People could not fulfil God’s word, because they were sinners; the law pointed ahead to the one who would.'],
      ['p', 'Moses was faithful in God’s house as a servant. Christ is faithful over God’s house as a son. In the ancient world a son was the heir: the relationship between father and son carried the inheritance, the authority and the benefits of the house. The servant works in the house; the son is over it.'],
      ['h', 'We are his house'],
      ['p', 'Verse 6 can sound like a condition: hold on, and then you become God’s house. It is the other way round. Holding fast our confidence and our boasting in hope is the evidence that we already are his house. Perseverance does not make us God’s house; it reveals us as God’s house.']] },
  ko: { title: '예수를 깊이 생각하십시오', quote: '“그리스도는 아들로서, 하나님의 집안 사람을 성실하게 돌보셨습니다.”', sref: '히브리서 3:6', cap: '장면: 모세 시대 하나님의 집인 성막이 광야에 세워지고, 주님의 영광이 그 위에 머뭅니다.',
    snips: ['우리가 고백하는 신앙의 사도요, 대제사장이신 예수를 깊이 생각하십시오', '모세가 하나님의 온 집안에 성실했던 것과 같이', '집을 지은 사람이 집보다 더 존귀한 것과 같이', '모든 것을 지으신 분은 하나님이십니다', '장차 말씀하시려는 것을 증언하기 위한 일꾼', '그리스도는 아들로서… 우리는 하나님의 집안 사람입니다'],
    verses: [
      [1, '그러므로 [calling|하늘의 부르심]을 함께 받은 [holy|거룩한] 형제자매 여러분, 우리가 [confession|고백하는] 신앙의 [apostle|사도]요, [priest|대제사장]이신 예수를 [consider|깊이 생각하십시오].'],
      [2, '이 예수는 모세가 [house|하나님의 온 집안]에 성실했던 것과 같이, 자기를 세우신 분께 [faithful|성실하셨습니다].'],
      [3, '[builder|집을 지은 사람]이 집보다 더 존귀한 것과 같이, 예수는 모세보다 더 큰 [glory|영광]을 누리기에 합당한 분이십니다.'],
      [4, '어떠한 집이든지 어떤 사람이 짓습니다. 그러나 모든 것을 지으신 분은 하나님이십니다.'],
      [5, '모세는, 하나님께서 장차 말씀하시려는 것을 증언하기 위한 [servant|일꾼]으로서, 하나님의 온 집안 사람에게 성실하였습니다.'],
      [6, '그러나 그리스도는 [son|아들]로서, 하나님의 집안 사람을 성실하게 돌보셨습니다. 우리가 그 소망에 대하여 [confidence|확신]과 [boasting|자부심]을 지니고 있으면, 우리는 하나님의 집안 사람입니다.']],
    com: [['h', '그러므로, 예수를 깊이 생각하십시오'],
      ['p', '3장은 “그러므로”로 시작합니다. 2장에서 이어지는 말입니다. 거기서 예수님은 피와 살을 함께 지니시고, 죽음을 맛보시고, 그 세력을 깨뜨리셨으며, 몸소 시험을 받고 이기셨기에 시험받는 사람들을 도우실 수 있는 자비롭고 성실한 대제사장이 되셨습니다. 그래서 저자는 말합니다. 그분을 깊이 생각하십시오. NLT는 “이 예수님을 주의 깊게 생각하십시오”로, NIV는 “예수님께 생각을 고정하십시오”로 옮깁니다.'],
      ['p', '독자들은 하나님께 구별된 거룩한 사람들이라 불리며, 이미 하늘의 부르심, 곧 “장차 올 세상”(2:5)의 영원한 구원으로 부르시는 하나님의 초대를 함께 받았습니다. 바로 그렇기 때문에 예수님께 마음을 두어야 합니다. 복음을 듣고 하늘로 가는 길을 받았으면서도, 그분을 생각하기를 멈출 수 있기 때문입니다. 예수님은 사도, 곧 하나님께서 온전한 권위를 주어 보내신 분이시며, 대제사장, 곧 하나님과 그 백성 사이에 서신 분이십니다. 우리의 고백은 우리가 함께 드러내어 선포하는 것, 곧 예수님이 주님이시라는 것입니다.'],
      ['h', '집안에서 성실했던 모세'],
      ['p', '모세는 이스라엘 역사에서 가장 중요한 인물 가운데 하나입니다. 하나님은 그를 예언자로 세우시고, 환상이나 꿈이나 수수께끼가 아니라 얼굴을 마주하여 분명하게 말씀하셨습니다(민 12:6–8). 그는 시내 산에서 돌판에 새긴 율법을 받았고, 구약의 첫 다섯 책인 모세오경을 기록했습니다. 그리고 하나님의 온 집안에 성실했습니다.'],
      ['p', '모세 시대에 “하나님의 집”은 공동체가 예배하던 성막이었습니다. 그러나 집은 건물 그 이상입니다. 예배하러 모인 사람들이기도 합니다. 눈에 보이는 장소이자 영적인 공동체입니다. 모든 집에는 지은 사람이 있고, 모든 것을 지으신 분은 하나님이십니다. 성막도, 그 안에서 예배하는 사람들도 그분이 지으셨습니다. 하나님께서 그를 통하여 온 세상을 지으신 예수님(1:2)도 그 집을 지으신 분이시며, 집을 지은 이는 집보다 더 존귀합니다.'],
      ['h', '일꾼과 아들'],
      ['p', '모세는 “테라폰”으로 섬겼습니다. 흔한 종이 아니라 자원하여 섬기며 주인의 일을 진심으로 돌보는 일꾼입니다. 그의 역할은 섬기는 것만이 아니라, “장차 말씀하시려는 것”, 곧 하나님께서 이 마지막 날에 아들을 통하여 하실 말씀(1:2)을 증언하는 것이었습니다. 율법은 예수님을 미리 보여 주는 그림자였습니다. 사람은 죄인이기에 하나님의 말씀을 다 이룰 수 없었고, 율법은 그것을 이루실 분을 가리켰습니다.'],
      ['p', '모세는 일꾼으로서 하나님의 집안에서 성실했습니다. 그리스도는 아들로서 하나님의 집안을 다스리며 성실하게 돌보십니다. 고대 세계에서 아들은 상속자였습니다. 아버지와 아들의 관계에는 유업과 권위와 집안의 모든 유익이 담겨 있었습니다. 일꾼은 집 안에서 일하고, 아들은 그 집 위에 있습니다.'],
      ['h', '우리가 그분의 집입니다'],
      ['p', '6절은 조건처럼 들릴 수 있습니다. 붙들고 있으면 그때 하나님의 집이 된다는 것처럼요. 사실은 그 반대입니다. 소망에 대한 확신과 자부심을 지니고 있는 것이, 우리가 이미 그분의 집이라는 증거입니다. 인내가 우리를 하나님의 집으로 만드는 것이 아니라, 우리가 하나님의 집임을 드러내 줍니다.']] },
  words: {
    en: {
      holy: { t: 'Holy', g: 'hagioi · ἅγιοι', v: '3:1', s: 'Set apart for God', d: 'Different, set apart, distinct; set apart for or by God, and so able to be brought near, into his holy presence.' },
      calling: { t: 'Heavenly calling', g: 'klēseōs epouraniou metochoi · κλήσεως ἐπουρανίου μέτοχοι', v: '3:1', s: 'God’s invitation to salvation', d: 'Sharing in, partaking of something. Here, the calling or invitation made by God in heaven: the divine invitation to eternal salvation in “the world to come” (2:5).' },
      consider: { t: 'Consider', g: 'katanoēsate · κατανοήσατε', v: '3:1', s: 'Fix the mind on, observe carefully', d: 'To put the mind down on something, and so to observe or consider it carefully and attentively. NLT: “think carefully about this Jesus”; NIV: “fix your thoughts on Jesus.”' },
      apostle: { t: 'Apostle', g: 'apostolos · ἀπόστολος', v: '3:1', s: 'God’s chief messenger', d: 'A delegate, commissioner or ambassador, sent out on a mission with the authority of the one who sent him. Jesus is God’s chief messenger.' },
      priest: { t: 'High priest', g: 'archiereus · ἀρχιερεύς', v: '3:1', s: 'Mediator between God and his people', d: 'The chief over all the other priests in Israel, established by God through Moses. He mediated between God and Israel, offered sacrifices, and once a year represented the sins of the nation in the Most Holy Place.' },
      confession: { t: 'Confession', g: 'homologia · ὁμολογία', v: '3:1', s: 'What we openly declare together', d: 'To say the same thing, to agree in one’s statement; to declare openly, speaking out freely. Our shared confession that Jesus is Lord.' },
      faithful: { t: 'Faithful', g: 'pistos · πιστός', v: '3:2', s: 'Trustworthy in his charge', d: 'Trustworthy; one who shows himself faithful in business, in carrying out commands, in official duties. Jesus served faithfully the God who appointed him.' },
      house: { t: 'God’s house', g: 'oikos · οἶκος', v: '3:2', s: 'The place and the people', d: 'In Moses’ time, the tabernacle where the community worshipped. The house is also the people: both the physical place and the spiritual community.' },
      glory: { t: 'Glory', g: 'doxa · δόξα', v: '3:3', s: 'Honour, worthy of praise', d: 'A source of honour, fame or admiration; something beautiful, impressive or worthy of praise.' },
      builder: { t: 'Builder', g: 'kataskeuasas · κατασκευάσας', v: '3:3', s: 'The one who built and furnished it', d: 'The one who prepares, builds and furnishes a house. God built the tabernacle and the people who worshipped in it, and Jesus, through whom all things were made, is its builder too.' },
      servant: { t: 'Servant', g: 'therapōn · θεράπων', v: '3:5', s: 'One who serves willingly', d: 'Not the ordinary slave (doulos) but one who serves willingly, who deeply regards his superior’s interests and looks after his affairs, whether free or not. A higher position than a common slave.' },
      son: { t: 'Son', g: 'huios · υἱός', v: '3:6', s: 'The heir, over the house', d: 'The son was the heir. The father–son relationship carried the inheritance, authority and benefits of the house. Moses served in the house; the Son is over it.' },
      confidence: { t: 'Confidence', g: 'parrēsia · παρρησία', v: '3:6', s: 'Boldness without fear', d: 'Freedom of speech; an attitude of openness that comes from freedom and a lack of fear.' },
      boasting: { t: 'Boasting', g: 'kauchēma · καύχημα', v: '3:6', s: 'Glorying in what is ours', d: 'To boast over a privilege or possession. NLT: “if we keep our courage and remain confident in our hope in Christ.”' } },
    ko: {
      holy: { t: '거룩한', g: 'hagioi · ἅγιοι', v: '3:1', s: '하나님께 구별됨', d: '다른, 구별된, 따로 떼어 놓은. 하나님을 위하여, 하나님에 의해 구별되어 그분의 거룩한 임재 가까이 나아갈 수 있는.' },
      calling: { t: '하늘의 부르심', g: 'klēseōs epouraniou metochoi · κλήσεως ἐπουρανίου μέτοχοι', v: '3:1', s: '구원으로 부르시는 하나님의 초대', d: '어떤 것에 함께 참여하는 것. 여기서는 하늘에 계신 하나님께서 하신 부르심, 곧 “장차 올 세상”(2:5)의 영원한 구원으로의 초대입니다.' },
      consider: { t: '깊이 생각하다', g: 'katanoēsate · κατανοήσατε', v: '3:1', s: '마음을 고정하여 주의 깊게 봄', d: '어떤 것에 마음을 내려놓고, 주의 깊고 세심하게 살피고 생각하는 것. NLT: “이 예수님을 주의 깊게 생각하십시오.” NIV: “예수님께 생각을 고정하십시오.”' },
      apostle: { t: '사도', g: 'apostolos · ἀπόστολος', v: '3:1', s: '하나님의 으뜸 사자', d: '보낸 이의 권위를 가지고 사명을 받아 보내진 대리인, 사절, 대사. 예수님은 하나님의 으뜸 사자이십니다.' },
      priest: { t: '대제사장', g: 'archiereus · ἀρχιερεύς', v: '3:1', s: '하나님과 백성 사이의 중재자', d: '이스라엘의 모든 제사장 위에 있는 우두머리로, 하나님께서 모세를 통해 세우셨습니다. 하나님과 이스라엘 사이를 중재하고 제사를 드렸으며, 해마다 한 번 지성소에서 민족의 죄를 대신하여 섰습니다.' },
      confession: { t: '고백', g: 'homologia · ὁμολογία', v: '3:1', s: '함께 드러내어 선포하는 것', d: '같은 것을 말하다, 말에 동의하다. 자유롭게 드러내어 선언하는 것. 예수님이 주님이시라는 우리의 공통된 고백입니다.' },
      faithful: { t: '성실하다', g: 'pistos · πιστός', v: '3:2', s: '맡은 일에 믿음직함', d: '믿을 만한. 일을 처리하고 명령을 수행하고 직무를 감당하는 데 성실함을 보이는 사람. 예수님은 자기를 세우신 하나님께 성실하게 섬기셨습니다.' },
      house: { t: '하나님의 집안', g: 'oikos · οἶκος', v: '3:2', s: '장소이자 사람들', d: '모세 시대에는 공동체가 예배하던 성막이었습니다. 집은 사람들이기도 합니다. 눈에 보이는 장소이자 영적인 공동체입니다.' },
      glory: { t: '영광', g: 'doxa · δόξα', v: '3:3', s: '존귀, 찬양받기에 합당함', d: '존귀와 명성과 감탄의 근원. 아름답고 인상적이며 찬양받기에 합당한 것.' },
      builder: { t: '집을 지은 사람', g: 'kataskeuasas · κατασκευάσας', v: '3:3', s: '집을 짓고 갖춘 이', d: '집을 준비하고 짓고 갖추는 사람. 하나님은 성막과 그 안에서 예배하는 사람들을 지으셨고, 만물이 그로 말미암아 지어진 예수님도 그 집을 지으신 분이십니다.' },
      servant: { t: '일꾼', g: 'therapōn · θεράπων', v: '3:5', s: '자원하여 섬기는 사람', d: '보통의 종(둘로스)이 아니라, 자유인이든 아니든 자원하여 섬기며 윗사람의 일을 깊이 마음에 두고 돌보는 사람. 흔한 종보다 높은 자리입니다.' },
      son: { t: '아들', g: 'huios · υἱός', v: '3:6', s: '상속자, 집을 다스림', d: '아들은 상속자였습니다. 아버지와 아들의 관계에는 유업과 권위와 집안의 유익이 담겨 있었습니다. 모세는 집 안에서 섬겼고, 아들은 그 집 위에 계십니다.' },
      confidence: { t: '확신', g: 'parrēsia · παρρησία', v: '3:6', s: '두려움 없는 담대함', d: '말의 자유. 자유와 두려움 없음에서 나오는 열린 태도.' },
      boasting: { t: '자부심', g: 'kauchēma · καύχημα', v: '3:6', s: '우리에게 주신 것을 자랑함', d: '받은 특권이나 소유를 자랑하는 것. NLT: “우리가 용기를 잃지 않고 그리스도 안에서 소망을 확신하면.”' } } },
  chips: [
    { id: 'num12', tag: 'OT', en: 'Num 12:7', ko: '민 12:7', ten: 'Not so with my servant Moses. He is faithful in all my house.', tko: '나의 종 모세는 다르다. 그는 나의 온 집을 충성스럽게 맡고 있다.', wen: 'God’s own word about Moses, which Hebrews 3:2 and 3:5 echo.', wko: '모세에 대한 하나님의 말씀으로, 히브리서 3:2과 3:5이 이 말씀을 되울립니다.' },
    { id: 'heb1', tag: 'NT', en: 'Heb 1:2', ko: '히 1:2', ten: 'But in these last days he has spoken to us by his Son, whom he appointed the heir of all things, through whom also he created the world.', tko: '이 마지막 날에는 아들을 통하여 우리에게 말씀하셨습니다. 하나님께서는 이 아들을 만물의 상속자로 세우셨습니다. 그를 통하여 온 세상을 지으신 것입니다.', wen: 'The “things to be spoken later” that Moses testified to. The Son is heir and builder.', wko: '모세가 증언한 “장차 말씀하시려는 것”. 아들은 상속자이시며 지으신 분입니다.' },
    { id: 'pet2', tag: 'NT', en: '1 Pet 2:5', ko: '벧전 2:5', ten: 'You yourselves like living stones are being built up as a spiritual house, to be a holy priesthood, to offer spiritual sacrifices acceptable to God through Jesus Christ.', tko: '살아 있는 돌과 같은 존재로서 여러분도 집 짓는 데 사용되어 신령한 집이 됩니다. 그래서 여러분은 예수 그리스도로 말미암아 하나님께서 기쁘게 받으실 신령한 제사를 드리는 거룩한 제사장이 되십니다.', wen: '“We are his house”: God’s people as living stones.', wko: '“우리는 하나님의 집안 사람입니다”: 살아 있는 돌인 하나님의 백성.' }] },

{ id: 'm2', num: 'II', range: '7–11', scene: 'rock', art: '3D · R3F — dunes under a dusk sky; a cleft rock stands alone. Light breaks from the cleft and water spills down it and spreads across the sand.',
  en: { title: 'Today, if you hear his voice', quote: '“Today, if you hear his voice, do not harden your hearts as in the rebellion.”', sref: 'Hebrews 3:7–8', cap: 'Scene: a rock in a dry wilderness. Water pours out of it, and still they tested him.',
    snips: ['As the Holy Spirit says, “Today, if you hear his voice”', '“Do not harden your hearts as in the rebellion”', '“They saw my works for forty years”', '“They always go astray in their heart”', '“They shall not enter my rest”'],
    verses: [
      [7, 'Therefore, as the Holy Spirit says, “Today, if you [hear|hear his voice],'],
      [8, 'do not [harden|harden your hearts] as in the [rebellion|rebellion], on the day of testing in the wilderness,'],
      [9, 'where your fathers put me to the test and saw my works for forty years.'],
      [10, 'Therefore I was provoked with that generation, and said, ‘They always go astray in their heart; they have not known my ways.’'],
      [11, 'As I swore in my wrath, ‘They shall not enter my [rest|rest].’”']],
    com: [['h', 'As the Holy Spirit says'],
      ['p', 'The author quotes Psalm 95, but he does not say “as David wrote.” He says “as the Holy Spirit says,” in the present tense. The psalm is an ancient Jewish hymn sung in public worship, and through it God is still speaking to his people today.'],
      ['h', 'Massah and Meribah'],
      ['p', 'After God brought the Israelites out of Egypt through Moses, they grumbled almost at once. At Marah in the wilderness of Shur the water was bitter, and they grumbled against Moses (Exod 15:23–24). God tested them there, to see whether they would listen to his voice and keep his commands (15:25–26). In the wilderness of Sin the whole community grumbled again: in Egypt, at least, they had bread and meat to eat.'],
      ['p', 'At Rephidim there was no water. The people quarrelled with Moses and tested the LORD, saying, “Is the LORD among us or not?” At Horeb God told Moses to strike the rock, and water flowed out of it. Moses named the place Massah (testing) and Meribah (quarrelling) (Exod 17:1–7). For forty years the pattern repeated: God gave them chances and warnings, and they saw his works, yet they kept grumbling and testing him.'],
      ['h', 'They shall not enter my rest'],
      ['p', 'Before Israel entered Canaan, Moses sent twelve leaders, one from each tribe, to spy out the land. Ten came back saying the people there were too strong to overcome. Only Joshua and Caleb trusted God’s word. Because of their unbelieving hearts, everyone twenty years old and over died in the wilderness. Joshua and Caleb, who believed God’s promise of deliverance, entered Canaan with the children (Num 13–14).'],
      ['p', 'Their hardened hearts cost them the Promised Land. They died physically, and spiritually too. The author’s warning to his readers is plain: do not repeat the wilderness generation’s mistake, and do not drift away from the truth. A good start does not guarantee a good finish.']] },
  ko: { title: '오늘 너희가 그의 음성을 듣거든', quote: '“오늘 너희가 그의 음성을 듣거든, … 너희 마음을 완고하게 하지 말아라.”', sref: '히브리서 3:7–8', cap: '장면: 메마른 광야의 바위. 거기서 물이 쏟아져 나오는데도, 그들은 하나님을 시험했습니다.',
    snips: ['성령이 이와 같이 말씀하셨습니다. “오늘 너희가 그의 음성을 듣거든”', '“너희 마음을 완고하게 하지 말아라”', '“사십 년 동안이나 내가 하는 일들을 보았다”', '“그들은 언제나 마음이 미혹되어서”', '“그들은 결코 내 안식에 들어오지 못할 것이다”'],
    verses: [
      [7, '그러므로 성령이 이와 같이 말씀하셨습니다. “오늘 너희가 [hear|그의 음성을 듣거든],'],
      [8, '너희 조상들이 광야에서 시험받던 날에 [rebellion|반역한] 것과 같이, [harden|너희 마음을 완고하게] 하지 말아라.'],
      [9, '거기에서 그들은 나를 시험하여 보았고, 사십 년 동안이나 내가 하는 일들을 보았다.'],
      [10, '그러므로 나는 그 세대에게 분노해서 말하였다. ‘그들은 언제나 마음이 미혹되어서 내 길을 알지 못하였다.’'],
      [11, '내가 진노하여 맹세한 대로 그들은 결코 [rest|내 안식]에 들어오지 못할 것이다.”']],
    com: [['h', '성령이 말씀하셨습니다'],
      ['p', '저자는 시편 95편을 인용하면서 “다윗이 썼다”고 하지 않고 “성령이 말씀하셨다”고 합니다. 이 시편은 공적인 예배에서 부르던 옛 유대인의 찬송이며, 하나님은 이 말씀을 통해 지금도 자기 백성에게 말씀하고 계십니다.'],
      ['h', '맛사와 므리바'],
      ['p', '하나님께서 모세를 통해 이스라엘 백성을 이집트에서 이끌어 내신 뒤, 그들은 곧바로 불평하기 시작했습니다. 수르 광야의 마라에서 물이 써서 마실 수 없자 모세에게 불평했습니다(출 15:23–24). 하나님은 거기서 그들이 그분의 음성을 듣고 계명을 지키는지 시험하셨습니다(15:25–26). 신 광야에서는 온 회중이 다시 불평했습니다. 이집트에서는 적어도 빵과 고기를 먹었다는 것입니다.'],
      ['p', '르비딤에는 물이 없었습니다. 백성은 모세와 다투고 “주님께서 우리 가운데 계시는가, 안 계시는가?” 하며 주님을 시험했습니다. 호렙에서 하나님은 모세에게 바위를 치라고 하셨고, 거기서 물이 흘러나왔습니다. 모세는 그곳을 맛사(시험함)와 므리바(다툼)라고 불렀습니다(출 17:1–7). 사십 년 동안 같은 일이 되풀이되었습니다. 하나님은 기회와 경고를 주셨고 그들은 그분이 하시는 일을 보았지만, 여전히 불평하며 그분을 시험했습니다.'],
      ['h', '결코 내 안식에 들어오지 못할 것이다'],
      ['p', '가나안에 들어가기 전, 모세는 각 지파에서 지도자 한 사람씩 열두 명을 뽑아 그 땅을 정탐하게 했습니다. 열 명은 그 땅 백성이 너무 강해서 차지할 수 없다고 말했습니다. 여호수아와 갈렙만이 하나님의 말씀을 신뢰했습니다. 결국 믿지 않는 마음 때문에 스무 살 이상 된 사람은 모두 광야에서 죽었고, 하나님의 구원의 약속을 믿은 여호수아와 갈렙은 자녀들과 함께 가나안에 들어갔습니다(민 13–14장).'],
      ['p', '완고한 마음 때문에 그들은 약속의 땅을 잃었습니다. 육체로 죽었고, 영적으로도 죽었습니다. 저자가 독자들에게 주는 경고는 분명합니다. 광야 세대의 실수를 되풀이하지 말고, 진리에서 떠내려가지 마십시오. 좋은 출발이 좋은 끝을 보장하지는 않습니다.']] },
  words: {
    en: {
      hear: { t: 'Hear his voice', g: 'akousēte · ἀκούσητε', v: '3:7', s: 'To hear and respond', d: 'To perceive the distinct words of a voice. Not mere listening or auditory exposure, but hearing that responds: here, to God’s voice.' },
      harden: { t: 'Harden', g: 'sklērynēte · σκληρύνητε', v: '3:8', s: 'To make stubborn', d: 'Metaphorically, to render obstinate: refusing to change behaviour, plans or opinions even when others try to persuade you or give good reason to.' },
      rebellion: { t: 'Rebellion', g: 'parapikrasmos · παραπικρασμός', v: '3:8', s: 'Provoking God to bitterness', d: 'A provocation, an embittering. Psalm 95 names the places: Meribah (quarrelling) and Massah (testing), where Israel tested the LORD (Exod 17:7).' },
      rest: { t: 'My rest', g: 'katapausis · κατάπαυσις', v: '3:11', s: 'The promised land, and what it foreshadows', d: 'A place of rest. For Israel it was Canaan, the Promised Land. It foreshadows the kingdom of God: eternal salvation with Jesus.' } },
    ko: {
      hear: { t: '음성을 듣다', g: 'akousēte · ἀκούσητε', v: '3:7', s: '듣고 응답함', d: '음성의 말을 또렷이 알아듣는 것. 그저 귀에 들리는 것이 아니라 듣고 응답하는 것, 여기서는 하나님의 음성에 응답하는 것입니다.' },
      harden: { t: '완고하게 하다', g: 'sklērynēte · σκληρύνητε', v: '3:8', s: '고집스럽게 만듦', d: '비유적으로, 고집스럽게 만드는 것. 다른 사람이 설득하거나 합당한 이유를 주어도 행동이나 계획이나 생각을 바꾸지 않는 것.' },
      rebellion: { t: '반역', g: 'parapikrasmos · παραπικρασμός', v: '3:8', s: '하나님을 격노하시게 함', d: '격동시킴, 괴롭게 함. 시편 95편은 그 장소를 므리바(다툼)와 맛사(시험함)라고 부릅니다. 이스라엘이 주님을 시험한 곳입니다(출 17:7).' },
      rest: { t: '내 안식', g: 'katapausis · κατάπαυσις', v: '3:11', s: '약속의 땅, 그리고 그것이 가리키는 것', d: '쉼의 자리. 이스라엘에게는 약속의 땅 가나안이었습니다. 그것은 하나님 나라, 곧 예수님과 함께하는 영원한 구원을 미리 보여 줍니다.' } } },
  chips: [
    { id: 'ps95', tag: 'OT', en: 'Ps 95:7–11', ko: '시 95:7–11', ten: 'For he is our God, and we are the people of his pasture, and the sheep of his hand. Today, if you hear his voice, do not harden your hearts, as at Meribah, as on the day at Massah in the wilderness, when your fathers put me to the test and put me to the proof, though they had seen my work. For forty years I loathed that generation and said, “They are a people who go astray in their heart, and they have not known my ways.” Therefore I swore in my wrath, “They shall not enter my rest.”', tko: '그는 우리의 하나님이시요, 우리는 그가 기르시는 백성이며, 그가 손수 이끄시는 양 떼다. 오늘, 너희는 그의 음성을 들어 보아라. “므리바에서처럼, 맛사 광야에 있을 때처럼, 너희의 마음을 완고하게 하지 말아라. 너희의 조상들은 그 때에, 내가 한 일을 보고서도, 나를 시험하고 또 시험하였다. 사십 년을 지나면서, 나는 그 세대를 보고 싫증이 나서 ‘그들은 마음이 빗나간 백성이요, 나의 길을 깨닫지 못하는 자들이구나’ 하였고, 내가 화가 나서 ‘그들은 나의 안식에 들어오지 못할 것이다’ 하고 맹세까지 하였다.”', wen: 'The psalm Hebrews 3:7–11 quotes, an ancient hymn of public worship.', wko: '히브리서 3:7–11이 인용하는 시편으로, 공적인 예배에서 부르던 옛 찬송입니다.' },
    { id: 'exod17', tag: 'OT', en: 'Exod 17:7', ko: '출 17:7', ten: 'And he called the name of the place Massah and Meribah, because of the quarreling of the people of Israel, and because they tested the LORD by saying, “Is the LORD among us or not?”', tko: '이스라엘 자손이 거기에서 주님께 대들었다고 해서, 사람들은 그 곳의 이름을 므리바라고도 하고, 또 거기에서 “주님께서 우리 가운데 계시는가, 안 계시는가?” 하면서 주님을 시험하였다고 해서, 그 곳의 이름을 맛사라고도 한다.', wen: 'Water from the rock at Horeb, and the names the place was given.', wko: '호렙의 바위에서 나온 물, 그리고 그곳에 붙은 이름.' }] },

{ id: 'm3', num: 'III', range: '12–15', scene: 'coals', art: '3D · R3F — a bed of glowing coals; one coal rolls out on its own, its glow fading to grey ash, until it is drawn back among the others and catches again.',
  en: { title: 'Exhort one another every day', quote: '“But exhort one another every day, as long as it is called ‘today.’”', sref: 'Hebrews 3:13', cap: 'Scene: a coal taken out of the fire goes cold. Brought back among the others, it glows again.',
    snips: ['Lest there be in any of you an evil, unbelieving heart', 'Exhort one another every day, as long as it is called “today”', 'We have come to share in Christ, if we hold firm to the end', '“Today, if you hear his voice, do not harden your hearts”'],
    verses: [
      [12, '[takecare|Take care], brothers, lest there be in any of you an [evil|evil], [unbelieving|unbelieving] [heart|heart], leading you to [fallaway|fall away] from the living God.'],
      [13, 'But [exhort|exhort one another] every day, as long as it is called “[today|today],” that none of you may be [hardened|hardened] by the [deceit|deceitfulness] of [sin|sin].'],
      [14, 'For we have come to [share|share in Christ], if indeed we hold our original confidence firm to the [end|end].'],
      [15, 'As it is said, “Today, if you hear his voice, do not harden your hearts as in the rebellion.”']],
    com: [['h', 'An unbelieving heart'],
      ['p', '“Take care” means keep a watchful eye always open. The danger is an evil, unbelieving heart, and it grows gradually. The verse says “leading you to fall away” (NLT, “turning you away”). As a heart lacks faith more and more, in the end that person falls away from the living God.'],
      ['p', 'It is striking that the author says “living God.” God is living, past, present and future. The God who dealt with Israel in the wilderness is the same God today, so to fall away from him is to face the same consequences they did.'],
      ['h', 'Exhort one another'],
      ['p', 'Verse 13 begins with “but”, the answer to verse 12. To exhort is to call someone alongside: to urge them to act, and to help them meet a hard situation with confidence and courage. Only by exhorting one another can believers keep from being hardened, another gradual word, by the deceitfulness of sin. Sin means missing the mark: missing God’s will for us, obeying the flesh rather than the Holy Spirit. And it deceives, giving a false impression and leading astray with false promises.'],
      ['p', 'The readers were living through hardship, suffering and difficult times, when it is easy to fall away from God. Hardship breeds unbelief, and unbelief ends in rebellion. So the author tells them not to be fooled by sin’s good appearance, and to encourage one another every day. It is a community effort, not an individual one (공동체). And it cannot wait. “Today” means now.'],
      ['h', 'Proof, not payment'],
      ['p', 'Verse 14 repeats the logic of verse 6. Holding our original confidence firm to the end, the hope of salvation we had when we first believed the gospel, is the evidence that we have come to share in Christ. Perseverance is not the payment that earns salvation. It is the proof that we are saved, that we are God’s people, the adelphoi of Jesus Christ.'],
      ['p', 'Paul teaches that we are saved by faith alone, not by doing good or keeping religious laws. Jesus already paid the price on the cross; the only question is whether we receive his free gift by faith. Hebrews adds that true faith lasts to the very end. Once you have entered, you do not stand at the start line; you move your feet toward the finish. You do not buy a trophy at the end of the race. You run the race, and that shows you are a real runner.']] },
  ko: { title: '날마다 서로 권면하십시오', quote: '“‘오늘’이라고 하는 그날그날, 서로 권면하여”', sref: '히브리서 3:13', cap: '장면: 불에서 떨어져 나온 숯은 식어 갑니다. 다른 숯들 곁으로 돌아오면, 다시 타오릅니다.',
    snips: ['믿지 않는 악한 마음을 품고서… 떠나는 사람이 아무도 없도록', '‘오늘’이라고 하는 그날그날, 서로 권면하여', '처음 가졌던 확신을 끝까지 가지고 있으면', '“오늘 너희가 그의 음성을 듣거든”'],
    verses: [
      [12, '형제자매 여러분, 여러분 가운데에 [unbelieving|믿지 않는] [evil|악한] [heart|마음]을 품고서, 살아 계신 하나님을 [fallaway|떠나는] 사람이 아무도 없도록, 여러분은 [takecare|조심하십시오].'],
      [13, '‘[today|오늘]’이라고 하는 그날그날, [exhort|서로 권면하여], 아무도 [sin|죄]의 [deceit|유혹]에 빠져 [hardened|완고하게] 되지 않도록 하십시오.'],
      [14, '우리가 처음 믿을 때에 가졌던 확신을 [end|끝까지] 가지고 있으면, 우리는 [share|그리스도께서 주시는 구원을 함께 누리는] 사람이 될 것입니다.'],
      [15, '“오늘 너희가 그의 음성을 듣거든, 반역하던 때와 같이 너희의 마음을 완고하게 하지 말아라” 하는 말씀이 있는데,']],
    com: [['h', '믿지 않는 마음'],
      ['p', '“조심하십시오”는 늘 눈을 뜨고 지켜보라는 뜻입니다. 위험은 믿지 않는 악한 마음이며, 그것은 서서히 자랍니다. 원문은 “떠나게 이끄는”이라고 말합니다(NLT, “여러분을 돌아서게 하는”). 마음에 믿음이 점점 사라지면, 결국 그 사람은 살아 계신 하나님을 떠나게 됩니다.'],
      ['p', '저자가 “살아 계신 하나님”이라고 말하는 것이 눈에 띕니다. 하나님은 과거에도 현재에도 미래에도 살아 계십니다. 광야에서 이스라엘을 다루신 하나님이 오늘도 같은 하나님이시니, 그분을 떠나는 사람은 그들과 같은 결과를 맞게 됩니다.'],
      ['h', '서로 권면하십시오'],
      ['p', '13절은 12절에 대한 답으로 시작합니다. 권면한다는 것은 누군가를 곁으로 부르는 것입니다. 행동하도록 촉구하고, 어려운 상황을 확신과 용기로 맞설 수 있도록 돕는 것입니다. 서로 권면해야만 죄의 유혹에 빠져 완고하게 되는 것, 역시 서서히 진행되는 일을 막을 수 있습니다. 죄는 과녁을 빗나가는 것, 곧 우리를 향한 하나님의 뜻을 놓치고 성령이 아니라 육신을 따르는 것입니다. 그리고 죄는 속입니다. 그럴듯한 겉모습과 거짓 약속으로 길을 잃게 합니다.'],
      ['p', '독자들은 어려움과 고난 가운데 살고 있었고, 그런 때에는 하나님에게서 멀어지기 쉽습니다. 어려움은 불신을 낳고, 불신은 반역으로 끝납니다. 그래서 저자는 죄의 그럴듯한 모습에 속지 말고 날마다 서로 격려하라고 말합니다. 혼자 하는 일이 아니라 공동체가 함께하는 일입니다. 그리고 미룰 수 없습니다. “오늘”은 바로 지금입니다.'],
      ['h', '값이 아니라 증거'],
      ['p', '14절은 6절의 논리를 되풀이합니다. 처음 복음을 믿을 때 가졌던 구원의 소망, 그 확신을 끝까지 붙드는 것이 우리가 그리스도께 함께 참여한 사람이라는 증거입니다. 인내는 구원을 사는 값이 아닙니다. 우리가 구원받은 사람, 하나님의 백성, 예수 그리스도의 형제자매(아델포이)라는 증거입니다.'],
      ['p', '바울은 우리가 선한 일이나 종교적 율법을 지켜서가 아니라 오직 믿음으로 구원받는다고 가르칩니다. 예수님께서 이미 십자가에서 값을 치르셨고, 남은 것은 그 값없는 선물을 믿음으로 받느냐 하는 것뿐입니다. 히브리서는 여기에 참된 믿음은 끝까지 간다고 덧붙입니다. 일단 들어섰으면 출발선에 서 있는 것이 아니라 결승선을 향해 발을 옮깁니다. 경주가 끝날 때 트로피를 사는 것이 아니라, 실제로 경주를 달려서 진짜 선수임을 보여 주는 것입니다.']] },
  words: {
    en: {
      takecare: { t: 'Take care', g: 'blepete · βλέπετε', v: '3:12', s: 'Keep a watchful eye open', d: 'To look to, in the sense of providing for; to be seeing to it constantly, keeping a watchful eye ever open.' },
      evil: { t: 'Evil', g: 'ponēra · πονηρά', v: '3:12', s: 'Actively opposed to good', d: 'Active evil, in opposition to good.' },
      unbelieving: { t: 'Unbelieving', g: 'apistias · ἀπιστίας', v: '3:12', s: 'Unwilling to trust', d: 'A lack of faith; distrust; unwillingness to commit oneself to another.' },
      heart: { t: 'Heart', g: 'kardia · καρδία', v: '3:12', s: 'The whole inner person', d: 'One’s personality, which controls the intellect, the emotions and the will.' },
      fallaway: { t: 'Fall away', g: 'apostēnai · ἀποστῆναι', v: '3:12', s: 'To become faithless', d: 'To stand off from, to depart; to become faithless. The NLT’s “turning you away” shows it happens gradually.' },
      exhort: { t: 'Exhort one another', g: 'parakaleite heautous · παρακαλεῖτε ἑαυτούς', v: '3:13', s: 'To call alongside and urge on', d: 'To call someone alongside, to oneself. Its main sense is to urge someone to take action; it also means to enable someone to meet a difficult situation with confidence and courage.' },
      today: { t: 'Today', g: 'sēmeron · σήμερον', v: '3:13', s: 'Now', d: 'The current day; now. Encouragement cannot wait.' },
      hardened: { t: 'Hardened', g: 'sklērynthē · σκληρυνθῇ', v: '3:13', s: 'Becoming unyielding', d: 'Used figuratively of becoming unyielding, obstinate or stubborn. Like “leading you to fall away,” it describes a gradual process.' },
      deceit: { t: 'Deceitfulness', g: 'apatē · ἀπάτη', v: '3:13', s: 'A false impression', d: 'A false impression, whether by appearance, statement or influence; anything that leads astray by persuasion or false promises.' },
      sin: { t: 'Sin', g: 'hamartia · ἁμαρτία', v: '3:13', s: 'Missing the mark', d: 'Missing the mark: missing God’s will for us; listening to and obeying the flesh rather than the Holy Spirit.' },
      share: { t: 'Share in Christ', g: 'metochoi tou Christou · μέτοχοι τοῦ Χριστοῦ', v: '3:14', s: 'Partakers of Christ', d: 'One who has a share in the possession of something, here Christ himself. The same word as “share in a heavenly calling” in 3:1. NLT: “we will share in all that belongs to Christ.”' },
      end: { t: 'To the end', g: 'mechri telous · μέχρι τέλους', v: '3:14', s: 'Completion, the goal reached', d: 'Termination, completion, the goal achieved. NLT: “if we are faithful to the end, trusting God just as firmly as when we first believed.”' } },
    ko: {
      takecare: { t: '조심하다', g: 'blepete · βλέπετε', v: '3:12', s: '늘 눈을 뜨고 살핌', d: '돌본다는 뜻에서 살피다. 늘 지켜보며 경계의 눈을 떼지 않는 것.' },
      evil: { t: '악한', g: 'ponēra · πονηρά', v: '3:12', s: '선에 맞서는 악', d: '선에 맞서는 적극적인 악.' },
      unbelieving: { t: '믿지 않는', g: 'apistias · ἀπιστίας', v: '3:12', s: '맡기지 않으려는 마음', d: '믿음이 없음, 불신, 자기를 다른 이에게 맡기지 않으려는 것.' },
      heart: { t: '마음', g: 'kardia · καρδία', v: '3:12', s: '속사람 전체', d: '지성과 감정과 의지를 다스리는 한 사람의 인격.' },
      fallaway: { t: '떠나다', g: 'apostēnai · ἀποστῆναι', v: '3:12', s: '믿음을 잃음', d: '떨어져 서다, 떠나다. 믿음을 잃는 것. NLT의 “돌아서게 하는”은 이것이 서서히 일어나는 일임을 보여 줍니다.' },
      exhort: { t: '서로 권면하다', g: 'parakaleite heautous · παρακαλεῖτε ἑαυτούς', v: '3:13', s: '곁으로 불러 북돋움', d: '누군가를 곁으로 부르는 것. 주된 뜻은 행동하도록 촉구하는 것이며, 어려운 상황을 확신과 용기로 맞서도록 돕는다는 뜻도 있습니다.' },
      today: { t: '오늘', g: 'sēmeron · σήμερον', v: '3:13', s: '지금', d: '바로 이날, 지금. 격려는 미룰 수 없습니다.' },
      hardened: { t: '완고하게 되다', g: 'sklērynthē · σκληρυνθῇ', v: '3:13', s: '굳어져 감', d: '비유적으로 굽히지 않고 고집스럽고 완고해지는 것. “떠나게 이끄는”처럼 서서히 진행되는 과정을 말합니다.' },
      deceit: { t: '유혹', g: 'apatē · ἀπάτη', v: '3:13', s: '거짓된 인상', d: '겉모습이나 말이나 영향으로 주는 거짓된 인상. 설득이나 거짓 약속으로 길을 잃게 하는 모든 것.' },
      sin: { t: '죄', g: 'hamartia · ἁμαρτία', v: '3:13', s: '과녁을 빗나감', d: '과녁을 빗나가는 것. 우리를 향한 하나님의 뜻을 놓치고, 성령이 아니라 육신에 귀 기울이고 따르는 것.' },
      share: { t: '함께 누리는 사람', g: 'metochoi tou Christou · μέτοχοι τοῦ Χριστοῦ', v: '3:14', s: '그리스도께 참여한 사람', d: '어떤 것을 함께 소유한 사람. 여기서는 그리스도 자신입니다. 3:1의 “하늘의 부르심을 함께 받은”과 같은 단어입니다. NLT: “그리스도께 속한 모든 것을 함께 누릴 것입니다.”' },
      end: { t: '끝까지', g: 'mechri telous · μέχρι τέλους', v: '3:14', s: '완성, 목표에 이름', d: '끝, 완성, 목표를 이룸. NLT: “처음 믿었을 때처럼 굳게 하나님을 신뢰하며 끝까지 신실하면.”' } } },
  chips: [
    { id: 'heb10', tag: 'NT', en: 'Heb 10:24–25', ko: '히 10:24–25', ten: 'And let us consider how to stir up one another to love and good works, not neglecting to meet together, as is the habit of some, but encouraging one another, and all the more as you see the Day drawing near.', tko: '그리고 서로 마음을 써서 사랑과 선한 일을 하도록 격려합시다. 어떤 사람들의 습관처럼, 우리는 모이기를 그만하지 말고, 서로 격려하여 그 날이 가까워 오는 것을 볼수록, 더욱 힘써 모입시다.', wen: 'The same call later in the letter: keep meeting, keep encouraging.', wko: '편지 뒷부분의 같은 부름: 계속 모이고, 계속 격려하십시오.' }] },

{ id: 'm4', num: 'IV', range: '16–19', scene: 'threshold', art: '3D · R3F — a line of small lights walks across a dark wilderness toward a lit land beyond a river; one by one they dim and settle in the sand, and only two cross into the light.',
  en: { title: 'Unable to enter because of unbelief', quote: '“So we see that they were unable to enter because of unbelief.”', sref: 'Hebrews 3:19', cap: 'Scene: a whole people walks toward the promised land. Most fall in the wilderness; two cross into the light.',
    snips: ['Was it not all those who left Egypt led by Moses?', 'Whose bodies fell in the wilderness', 'To whom did he swear that they would not enter his rest?', 'They were unable to enter because of unbelief'],
    verses: [
      [16, 'For who were those who heard and yet rebelled? Was it not all those who left Egypt led by Moses?'],
      [17, 'And with whom was he provoked for forty years? Was it not with those who sinned, whose bodies fell in the wilderness?'],
      [18, 'And to whom did he swear that they would not enter his [rest|rest], but to those who were [disobedient|disobedient]?'],
      [19, 'So we see that they were unable to enter because of [unbelief|unbelief].']],
    com: [['h', 'Those who heard, and rebelled'],
      ['p', 'The author turns back to the Exodus with three questions, to show where hardened hearts lead. Who heard and yet rebelled? Not strangers to God, but the very people Moses led out of Egypt, who had seen the plagues, the sea and the rock. With whom was God provoked for forty years? Those who sinned, whose bodies fell in the wilderness. To whom did he swear they would not enter his rest? Those who were disobedient.'],
      ['p', 'Instead of a faithful heart, they had hardened hearts, and the result was physical death and no entry into the Promised Land. That land foreshadows the kingdom of God with Jesus, eternal salvation. Their physical death foreshadows spiritual death and separation from God.'],
      ['h', 'God keeps his word'],
      ['p', 'God swore an oath that the unbelieving would not enter his rest. Later the letter shows how God binds himself by oath to his promises (6:13–20). His oath here shows the same faithfulness, and his judgement on those he warned who would not listen. The one thing that kept Israel out was unbelief: not a lack of strength, but a refusal to trust God.']] },
  ko: { title: '믿지 않았기 때문에 들어갈 수 없었습니다', quote: '“결국, 그들이 들어갈 수 없었던 것은 믿지 않았기 때문임을 우리는 압니다.”', sref: '히브리서 3:19', cap: '장면: 온 백성이 약속의 땅을 향해 걸어갑니다. 대부분은 광야에서 쓰러지고, 두 사람만 빛 속으로 건너갑니다.',
    snips: ['모세의 인도로 이집트에서 나온 사람들 모두가 아니었습니까?', '시체가 되어서 광야에 쓰러진 그 사람들', '누구에게 하나님의 안식에 들어가지 못하리라고 맹세하셨습니까?', '그들이 들어갈 수 없었던 것은 믿지 않았기 때문'],
    verses: [
      [16, '듣고서도 하나님께 반역한 사람들이 누구였습니까? 모세의 인도로 이집트에서 나온 사람들 모두가 아니었습니까?'],
      [17, '하나님께서 사십 년 동안 누구에게 진노하셨습니까? 죄를 짓고, 시체가 되어서 광야에 쓰러진 그 사람들이 아닙니까?'],
      [18, '하나님께서는 누구에게 [rest|하나님의 안식]에 들어가지 못하리라고 맹세하셨습니까? [disobedient|순종하지 않은] 사람들에게 하신 것이 아닙니까?'],
      [19, '결국, 그들이 들어갈 수 없었던 것은 [unbelief|믿지 않았기] 때문임을 우리는 압니다.']],
    com: [['h', '듣고서도 반역한 사람들'],
      ['p', '저자는 완고한 마음이 어디로 이끄는지 보여 주려고 세 가지 질문으로 다시 출애굽을 돌아봅니다. 듣고서도 반역한 사람들은 누구였습니까? 하나님을 모르는 사람들이 아니라, 모세가 이집트에서 이끌어 낸 바로 그 백성, 재앙과 바다와 바위를 직접 본 사람들이었습니다. 하나님께서 사십 년 동안 누구에게 진노하셨습니까? 죄를 짓고 광야에 쓰러진 사람들입니다. 누구에게 그분의 안식에 들어가지 못하리라고 맹세하셨습니까? 순종하지 않은 사람들입니다.'],
      ['p', '그들에게는 믿음의 마음 대신 완고한 마음이 있었고, 그 결과 육체로 죽고 약속의 땅에 들어가지 못했습니다. 그 땅은 예수님과 함께하는 하나님 나라, 곧 영원한 구원을 미리 보여 줍니다. 그들의 육체의 죽음은 영적 죽음, 곧 하나님과의 단절을 미리 보여 줍니다.'],
      ['h', '하나님은 말씀을 지키십니다'],
      ['p', '하나님은 믿지 않는 사람들이 그분의 안식에 들어가지 못하리라고 맹세하셨습니다. 편지 뒷부분은 하나님께서 맹세로 자기 약속에 스스로를 매신다는 것을 보여 줍니다(6:13–20). 이 맹세도 같은 신실하심을, 그리고 경고를 듣고도 귀 기울이지 않은 사람들에 대한 그분의 심판을 보여 줍니다. 이스라엘을 막은 단 한 가지는 불신이었습니다. 힘이 모자란 것이 아니라 하나님을 신뢰하지 않은 것입니다.']] },
  words: {
    en: {
      rest: { t: 'His rest', g: 'katapausis · κατάπαυσις', v: '3:18', s: 'The promised land, and what it foreshadows', d: 'A place of rest. For the wilderness generation, Canaan; for us, the kingdom of God with Jesus, eternal salvation.' },
      disobedient: { t: 'Disobedient', g: 'apeithēsasin · ἀπειθήσασιν', v: '3:18', s: 'Wilfully refusing', d: 'To wilfully and perversely refuse belief and obedience.' },
      unbelief: { t: 'Unbelief', g: 'apistia · ἀπιστία', v: '3:19', s: 'Faithlessness, distrust', d: 'Not believing; faithlessness, distrust, a lack of belief.' } },
    ko: {
      rest: { t: '하나님의 안식', g: 'katapausis · κατάπαυσις', v: '3:18', s: '약속의 땅, 그리고 그것이 가리키는 것', d: '쉼의 자리. 광야 세대에게는 가나안이었고, 우리에게는 예수님과 함께하는 하나님 나라, 곧 영원한 구원입니다.' },
      disobedient: { t: '순종하지 않은', g: 'apeithēsasin · ἀπειθήσασιν', v: '3:18', s: '고의로 거부함', d: '믿음과 순종을 고의로, 완강하게 거부하는 것.' },
      unbelief: { t: '믿지 않음', g: 'apistia · ἀπιστία', v: '3:19', s: '믿음 없음, 불신', d: '믿지 않는 것. 믿음 없음, 불신, 믿음의 결여.' } } },
  chips: [
    { id: 'num13', tag: 'OT', en: 'Num 13:30', ko: '민 13:30', ten: 'But Caleb quieted the people before Moses and said, “Let us go up at once and occupy it, for we are well able to overcome it.”', tko: '갈렙이 모세 앞에서 백성을 진정시키면서 격려하였다. “올라갑시다. 올라가서 그 땅을 점령합시다. 우리는 반드시 그 땅을 점령할 수 있습니다.”', wen: 'Ten spies saw giants; Caleb trusted God’s word.', wko: '열 명의 정탐꾼은 거인들을 보았고, 갈렙은 하나님의 말씀을 신뢰했습니다.' },
    { id: 'num14', tag: 'OT', en: 'Num 14:30', ko: '민 14:30', ten: 'Not one shall come into the land where I swore that I would make you dwell, except Caleb the son of Jephunneh and Joshua the son of Nun.', tko: '나는 너희에게 땅을 주어 살게 하겠다고, 손을 들어 맹세하였다. 그러나 이제 너희는 그 땅으로 들어가지 못할 것이다. 다만 여분네의 아들 갈렙과 눈의 아들 여호수아만이 들어갈 것이다.', wen: 'The oath of Hebrews 3:18, and the two who entered.', wko: '히브리서 3:18의 맹세, 그리고 들어간 두 사람.' },
    { id: 'cor10', tag: 'NT', en: '1 Cor 10:5', ko: '고전 10:5', ten: 'Nevertheless, with most of them God was not pleased, for they were overthrown in the wilderness.', tko: '그러나 그들의 대다수를 하나님께서는 좋아하지 않으셨습니다. 그들은 광야에서 멸망하고 말았습니다.', wen: 'Paul draws the same warning from the wilderness generation.', wko: '바울도 광야 세대에게서 같은 경고를 끌어냅니다.' }] }
];

const SUM: Record<Lang, Summary> = {
  en: { groups: [
      { h: 'Because you already belong', items: [['vv1–6', 'You share a heavenly calling, so fix your thoughts on Jesus. Moses was a faithful servant in God’s house; Jesus is the Son over it, and its builder. We are his house, and holding fast our hope shows it.']] },
      { h: 'Do not repeat the wilderness', items: [['vv7–11', 'Israel heard God’s voice and saw his works for forty years, yet hardened their hearts at Massah and Meribah and did not enter his rest.'], ['vv12–15', 'Watch for an unbelieving heart. Exhort one another every day, while it is called “today,” so that none of you is hardened by sin’s deceit.'], ['vv16–19', 'The very people who left Egypt fell in the wilderness. They were unable to enter because of unbelief.']] }],
    intentH: 'The author’s intention', intentShort: 'To urge believers who already belong to God’s house to fix their eyes on Jesus and hold their first confidence to the end, and not harden their hearts as Israel did in the wilderness.',
    intent: ['The readers already share in the heavenly calling, are already God’s house and already share in Christ. Because of that, they must fix their thoughts on Jesus and hold firmly to the confidence and hope they had when they first believed, all the way to the end, in these difficult times.', 'If they harden their hearts like their forefathers in the Exodus, they will not enter the promised eternal kingdom and will instead die a spiritual death. God made this clear through David: whoever does not believe and hardens their heart shall not enter his rest.', 'Perseverance is not how we earn salvation; it is the evidence that we have it. And it is not a solo effort: we exhort one another, every day, today.'] },
  ko: { groups: [
      { h: '이미 속해 있기에', items: [['1–6절', '하늘의 부르심을 함께 받았으니 예수를 깊이 생각하십시오. 모세는 하나님의 집안에서 성실한 일꾼이었고, 예수님은 그 집을 다스리시는 아들이시며 지으신 분이십니다. 우리는 그분의 집이며, 소망을 굳게 붙드는 것이 그 증거입니다.']] },
      { h: '광야를 되풀이하지 말라', items: [['7–11절', '이스라엘은 사십 년 동안 하나님의 음성을 듣고 그분이 하시는 일을 보았지만, 맛사와 므리바에서 마음을 완고하게 하여 그분의 안식에 들어가지 못했습니다.'], ['12–15절', '믿지 않는 마음을 조심하십시오. ‘오늘’이라고 하는 그날그날 서로 권면하여, 아무도 죄의 유혹에 빠져 완고하게 되지 않도록 하십시오.'], ['16–19절', '이집트에서 나온 바로 그 백성이 광야에서 쓰러졌습니다. 그들이 들어갈 수 없었던 것은 믿지 않았기 때문입니다.']] }],
    intentH: '저자의 의도', intentShort: '이미 하나님의 집에 속한 믿는 사람들에게, 예수님께 눈을 고정하고 처음 가졌던 확신을 끝까지 붙들며, 광야의 이스라엘처럼 마음을 완고하게 하지 말라고 권하는 것.',
    intent: ['독자들은 이미 하늘의 부르심을 함께 받았고, 이미 하나님의 집이며, 이미 그리스도께 함께 참여한 사람들입니다. 그렇기 때문에 이 어려운 때에 예수님께 생각을 고정하고, 처음 믿을 때 가졌던 확신과 소망을 끝까지 굳게 붙들어야 합니다.', '출애굽 때의 조상들처럼 마음을 완고하게 하면, 약속된 영원한 나라에 들어가지 못하고 영적 죽음을 맞게 됩니다. 하나님은 다윗을 통해 분명히 말씀하셨습니다. 믿지 않고 마음을 완고하게 하는 사람은 그분의 안식에 들어가지 못할 것입니다.', '인내는 구원을 얻는 방법이 아니라, 구원을 받았다는 증거입니다. 그리고 혼자 하는 일이 아닙니다. 우리는 서로 권면합니다. 날마다, 오늘.'] }
};

const COPY: Record<Lang, ChapterCopy> = {
  en: { heroEyebrow: 'A verse-by-verse study · ESV', heroTitle: 'Hebrews 3',
    tagline: '“Today, if you hear his voice, do not harden your hearts.”', taglineRef: 'Hebrews 3:7–8',
    mapTitle: 'Nineteen verses, four movements', mapIntro: 'Consider Jesus, the Son over God’s house. Then remember the wilderness: a people who heard God’s voice, hardened their hearts, and could not enter his rest.',
    summaryTitle: 'What Hebrews 3 says', footQuote: '“Exhort one another every day, as long as it is called ‘today.’”', version: 'ESV' },
  ko: { heroEyebrow: '한 절씩 읽는 성경 공부 · 새번역', heroTitle: '히브리서 3장',
    tagline: '“오늘 너희가 그의 음성을 듣거든, … 너희 마음을 완고하게 하지 말아라.”', taglineRef: '히브리서 3:7–8',
    mapTitle: '열아홉 절, 네 흐름', mapIntro: '하나님의 집을 다스리시는 아들, 예수를 깊이 생각하십시오. 그리고 광야를 기억하십시오. 하나님의 음성을 듣고도 마음을 완고하게 하여 그분의 안식에 들어가지 못한 백성을.',
    summaryTitle: '히브리서 3장이 말하는 것', footQuote: '“‘오늘’이라고 하는 그날그날, 서로 권면하여”', version: '새번역' }
};

export const chapter3: ChapterContent = { number: 3, setting: 'wilderness', copy: COPY, movements: MV, summary: SUM };
