import { chromium } from "@playwright/test";
const S = process.argv[2];
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(process.env.BASE_URL ?? "http://localhost:3000/", { waitUntil: "networkidle" });
await page.getByRole("button", { name: "한국어" }).click();
await page.waitForTimeout(800);
await page.screenshot({ path: `${S}/shots/ours-ko-hero.png` });
await page.evaluate(() => window.scrollTo(0, 2700));
await page.waitForTimeout(500);
await page.screenshot({ path: `${S}/shots/ours-ko-m1.png` });
await browser.close();
console.log("ko done");
